name = "cpsat-scheduler"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["CpsatScheduler"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
weak.linter.style.nativeDecide = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0-rc2"

[[require]]
name = "Regex"
git = "https://github.com/pandaman64/lean-regex"
rev = "v4.32.0"
subDir = "regex"

[[lean_lib]]
name = "CpsatScheduler"
