// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: commonpb/types.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskUnit indicates that the given value is in terms of the task's unit
type TaskUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskUnit) Reset() {
	*x = TaskUnit{}
	mi := &file_commonpb_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUnit) ProtoMessage() {}

func (x *TaskUnit) ProtoReflect() protoreflect.Message {
	mi := &file_commonpb_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskUnit.ProtoReflect.Descriptor instead.
func (*TaskUnit) Descriptor() ([]byte, []int) {
	return file_commonpb_types_proto_rawDescGZIP(), []int{0}
}

func (x *TaskUnit) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// AtomicUnit indicates that the given value is in terms of the atomic unit
type AtomicUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtomicUnit) Reset() {
	*x = AtomicUnit{}
	mi := &file_commonpb_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtomicUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicUnit) ProtoMessage() {}

func (x *AtomicUnit) ProtoReflect() protoreflect.Message {
	mi := &file_commonpb_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicUnit.ProtoReflect.Descriptor instead.
func (*AtomicUnit) Descriptor() ([]byte, []int) {
	return file_commonpb_types_proto_rawDescGZIP(), []int{1}
}

func (x *AtomicUnit) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AtomicInterval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *AtomicUnit            `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *AtomicUnit            `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtomicInterval) Reset() {
	*x = AtomicInterval{}
	mi := &file_commonpb_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtomicInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicInterval) ProtoMessage() {}

func (x *AtomicInterval) ProtoReflect() protoreflect.Message {
	mi := &file_commonpb_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicInterval.ProtoReflect.Descriptor instead.
func (*AtomicInterval) Descriptor() ([]byte, []int) {
	return file_commonpb_types_proto_rawDescGZIP(), []int{2}
}

func (x *AtomicInterval) GetStart() *AtomicUnit {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *AtomicInterval) GetEnd() *AtomicUnit {
	if x != nil {
		return x.End
	}
	return nil
}

type Interval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interval) Reset() {
	*x = Interval{}
	mi := &file_commonpb_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interval) ProtoMessage() {}

func (x *Interval) ProtoReflect() protoreflect.Message {
	mi := &file_commonpb_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interval.ProtoReflect.Descriptor instead.
func (*Interval) Descriptor() ([]byte, []int) {
	return file_commonpb_types_proto_rawDescGZIP(), []int{3}
}

func (x *Interval) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Interval) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_commonpb_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_commonpb_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_commonpb_types_proto_rawDescGZIP(), []int{4}
}

func (x *Entry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_commonpb_types_proto protoreflect.FileDescriptor

const file_commonpb_types_proto_rawDesc = "" +
	"\n" +
	"\x14commonpb/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\" \n" +
	"\bTaskUnit\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"\"\n" +
	"\n" +
	"AtomicUnit\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"R\n" +
	"\x0eAtomicInterval\x12!\n" +
	"\x05start\x18\x01 \x01(\v2\v.AtomicUnitR\x05start\x12\x1d\n" +
	"\x03end\x18\x02 \x01(\v2\v.AtomicUnitR\x03end\"j\n" +
	"\bInterval\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"+\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB7B\n" +
	"TypesProtoP\x01Z'cpsat-scheduler/internal/proto/commonpbb\x06proto3"

var (
	file_commonpb_types_proto_rawDescOnce sync.Once
	file_commonpb_types_proto_rawDescData []byte
)

func file_commonpb_types_proto_rawDescGZIP() []byte {
	file_commonpb_types_proto_rawDescOnce.Do(func() {
		file_commonpb_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commonpb_types_proto_rawDesc), len(file_commonpb_types_proto_rawDesc)))
	})
	return file_commonpb_types_proto_rawDescData
}

var file_commonpb_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_commonpb_types_proto_goTypes = []any{
	(*TaskUnit)(nil),              // 0: TaskUnit
	(*AtomicUnit)(nil),            // 1: AtomicUnit
	(*AtomicInterval)(nil),        // 2: AtomicInterval
	(*Interval)(nil),              // 3: Interval
	(*Entry)(nil),                 // 4: Entry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_commonpb_types_proto_depIdxs = []int32{
	1, // 0: AtomicInterval.start:type_name -> AtomicUnit
	1, // 1: AtomicInterval.end:type_name -> AtomicUnit
	5, // 2: Interval.start:type_name -> google.protobuf.Timestamp
	5, // 3: Interval.end:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_commonpb_types_proto_init() }
func file_commonpb_types_proto_init() {
	if File_commonpb_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commonpb_types_proto_rawDesc), len(file_commonpb_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commonpb_types_proto_goTypes,
		DependencyIndexes: file_commonpb_types_proto_depIdxs,
		MessageInfos:      file_commonpb_types_proto_msgTypes,
	}.Build()
	File_commonpb_types_proto = out.File
	file_commonpb_types_proto_goTypes = nil
	file_commonpb_types_proto_depIdxs = nil
}
