// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPossibleRelativesRequest_RelativeType int32

const (
	ListPossibleRelativesRequest_PARENT  ListPossibleRelativesRequest_RelativeType = 0
	ListPossibleRelativesRequest_CHILD   ListPossibleRelativesRequest_RelativeType = 1
	ListPossibleRelativesRequest_PREREQ  ListPossibleRelativesRequest_RelativeType = 2
	ListPossibleRelativesRequest_POSTREQ ListPossibleRelativesRequest_RelativeType = 3
)

// Enum value maps for ListPossibleRelativesRequest_RelativeType.
var (
	ListPossibleRelativesRequest_RelativeType_name = map[int32]string{
		0: "PARENT",
		1: "CHILD",
		2: "PREREQ",
		3: "POSTREQ",
	}
	ListPossibleRelativesRequest_RelativeType_value = map[string]int32{
		"PARENT":  0,
		"CHILD":   1,
		"PREREQ":  2,
		"POSTREQ": 3,
	}
)

func (x ListPossibleRelativesRequest_RelativeType) Enum() *ListPossibleRelativesRequest_RelativeType {
	p := new(ListPossibleRelativesRequest_RelativeType)
	*p = x
	return p
}

func (x ListPossibleRelativesRequest_RelativeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListPossibleRelativesRequest_RelativeType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_api_proto_enumTypes[0].Descriptor()
}

func (ListPossibleRelativesRequest_RelativeType) Type() protoreflect.EnumType {
	return &file_api_api_proto_enumTypes[0]
}

func (x ListPossibleRelativesRequest_RelativeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListPossibleRelativesRequest_RelativeType.Descriptor instead.
func (ListPossibleRelativesRequest_RelativeType) EnumDescriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{22, 0}
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PERT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pes           *durationpb.Duration   `protobuf:"bytes,1,opt,name=pes,proto3" json:"pes,omitempty"`
	Exp           *durationpb.Duration   `protobuf:"bytes,2,opt,name=exp,proto3" json:"exp,omitempty"`
	Opt           *durationpb.Duration   `protobuf:"bytes,3,opt,name=opt,proto3" json:"opt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PERT) Reset() {
	*x = PERT{}
	mi := &file_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PERT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PERT) ProtoMessage() {}

func (x *PERT) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PERT.ProtoReflect.Descriptor instead.
func (*PERT) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *PERT) GetPes() *durationpb.Duration {
	if x != nil {
		return x.Pes
	}
	return nil
}

func (x *PERT) GetExp() *durationpb.Duration {
	if x != nil {
		return x.Exp
	}
	return nil
}

func (x *PERT) GetOpt() *durationpb.Duration {
	if x != nil {
		return x.Opt
	}
	return nil
}

type DurState struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Pert     *PERT                  `protobuf:"bytes,1,opt,name=pert,proto3" json:"pert,omitempty"`
	Deadline *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	// zero if null
	TotalCost     int64 `protobuf:"varint,3,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurState) Reset() {
	*x = DurState{}
	mi := &file_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurState) ProtoMessage() {}

func (x *DurState) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurState.ProtoReflect.Descriptor instead.
func (*DurState) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *DurState) GetPert() *PERT {
	if x != nil {
		return x.Pert
	}
	return nil
}

func (x *DurState) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *DurState) GetTotalCost() int64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

type ChildrenConfigState struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Desc     string                 `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	Deadline *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	// zero if null
	ExpCost       int64    `protobuf:"varint,3,opt,name=exp_cost,json=expCost,proto3" json:"exp_cost,omitempty"`
	Children      []*Entry `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildrenConfigState) Reset() {
	*x = ChildrenConfigState{}
	mi := &file_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildrenConfigState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildrenConfigState) ProtoMessage() {}

func (x *ChildrenConfigState) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildrenConfigState.ProtoReflect.Descriptor instead.
func (*ChildrenConfigState) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *ChildrenConfigState) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ChildrenConfigState) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *ChildrenConfigState) GetExpCost() int64 {
	if x != nil {
		return x.ExpCost
	}
	return 0
}

func (x *ChildrenConfigState) GetChildren() []*Entry {
	if x != nil {
		return x.Children
	}
	return nil
}

type TaskState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Timescale     int64                  `protobuf:"varint,3,opt,name=timescale,proto3" json:"timescale,omitempty"`
	DurationCfg   *DurState              `protobuf:"bytes,4,opt,name=duration_cfg,json=durationCfg,proto3,oneof" json:"duration_cfg,omitempty"`
	ChildrenCfgs  []*ChildrenConfigState `protobuf:"bytes,5,rep,name=children_cfgs,json=childrenCfgs,proto3" json:"children_cfgs,omitempty"`
	Prereqs       []*Entry               `protobuf:"bytes,6,rep,name=prereqs,proto3" json:"prereqs,omitempty"`
	Postreqs      []*Entry               `protobuf:"bytes,7,rep,name=postreqs,proto3" json:"postreqs,omitempty"`
	Parent        *Entry                 `protobuf:"bytes,8,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start,proto3,oneof" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=end,proto3,oneof" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskState) Reset() {
	*x = TaskState{}
	mi := &file_api_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskState) ProtoMessage() {}

func (x *TaskState) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskState.ProtoReflect.Descriptor instead.
func (*TaskState) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *TaskState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskState) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *TaskState) GetTimescale() int64 {
	if x != nil {
		return x.Timescale
	}
	return 0
}

func (x *TaskState) GetDurationCfg() *DurState {
	if x != nil {
		return x.DurationCfg
	}
	return nil
}

func (x *TaskState) GetChildrenCfgs() []*ChildrenConfigState {
	if x != nil {
		return x.ChildrenCfgs
	}
	return nil
}

func (x *TaskState) GetPrereqs() []*Entry {
	if x != nil {
		return x.Prereqs
	}
	return nil
}

func (x *TaskState) GetPostreqs() []*Entry {
	if x != nil {
		return x.Postreqs
	}
	return nil
}

func (x *TaskState) GetParent() *Entry {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *TaskState) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TaskState) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

// CreateProfile
type CreateProfileRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AtomicTimescale *durationpb.Duration   `protobuf:"bytes,2,opt,name=atomic_timescale,json=atomicTimescale,proto3" json:"atomic_timescale,omitempty"`
	UniverseStart   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=universe_start,json=universeStart,proto3" json:"universe_start,omitempty"`
	GenPertChoices  int64                  `protobuf:"varint,4,opt,name=gen_pert_choices,json=genPertChoices,proto3" json:"gen_pert_choices,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_api_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProfileRequest) GetAtomicTimescale() *durationpb.Duration {
	if x != nil {
		return x.AtomicTimescale
	}
	return nil
}

func (x *CreateProfileRequest) GetUniverseStart() *timestamppb.Timestamp {
	if x != nil {
		return x.UniverseStart
	}
	return nil
}

func (x *CreateProfileRequest) GetGenPertChoices() int64 {
	if x != nil {
		return x.GenPertChoices
	}
	return 0
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_api_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{6}
}

type Profile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AtomicTimescale *durationpb.Duration   `protobuf:"bytes,3,opt,name=atomic_timescale,json=atomicTimescale,proto3" json:"atomic_timescale,omitempty"`
	UniverseStart   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=universe_start,json=universeStart,proto3" json:"universe_start,omitempty"`
	GenPertChoices  *int64                 `protobuf:"varint,5,opt,name=gen_pert_choices,json=genPertChoices,proto3,oneof" json:"gen_pert_choices,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_api_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{7}
}

func (x *Profile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetAtomicTimescale() *durationpb.Duration {
	if x != nil {
		return x.AtomicTimescale
	}
	return nil
}

func (x *Profile) GetUniverseStart() *timestamppb.Timestamp {
	if x != nil {
		return x.UniverseStart
	}
	return nil
}

func (x *Profile) GetGenPertChoices() int64 {
	if x != nil && x.GenPertChoices != nil {
		return *x.GenPertChoices
	}
	return 0
}

// ListProfiles
type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_api_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{8}
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Profile             `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_api_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{9}
}

func (x *ListProfilesResponse) GetEntries() []*Profile {
	if x != nil {
		return x.Entries
	}
	return nil
}

// RemoveProfile
type RemoveProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProfileRequest) Reset() {
	*x = RemoveProfileRequest{}
	mi := &file_api_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProfileRequest) ProtoMessage() {}

func (x *RemoveProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProfileRequest.ProtoReflect.Descriptor instead.
func (*RemoveProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveProfileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProfileResponse) Reset() {
	*x = RemoveProfileResponse{}
	mi := &file_api_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProfileResponse) ProtoMessage() {}

func (x *RemoveProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProfileResponse.ProtoReflect.Descriptor instead.
func (*RemoveProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{11}
}

// ReadTask
type ReadTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaskRequest) Reset() {
	*x = ReadTaskRequest{}
	mi := &file_api_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaskRequest) ProtoMessage() {}

func (x *ReadTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaskRequest.ProtoReflect.Descriptor instead.
func (*ReadTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{12}
}

func (x *ReadTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *TaskState             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaskResponse) Reset() {
	*x = ReadTaskResponse{}
	mi := &file_api_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaskResponse) ProtoMessage() {}

func (x *ReadTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaskResponse.ProtoReflect.Descriptor instead.
func (*ReadTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{13}
}

func (x *ReadTaskResponse) GetState() *TaskState {
	if x != nil {
		return x.State
	}
	return nil
}

// SaveTask
type SaveTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	ProfileId     int64                  `protobuf:"varint,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	State         *TaskState             `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTaskRequest) Reset() {
	*x = SaveTaskRequest{}
	mi := &file_api_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTaskRequest) ProtoMessage() {}

func (x *SaveTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTaskRequest.ProtoReflect.Descriptor instead.
func (*SaveTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{14}
}

func (x *SaveTaskRequest) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SaveTaskRequest) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *SaveTaskRequest) GetState() *TaskState {
	if x != nil {
		return x.State
	}
	return nil
}

type SaveTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTaskResponse) Reset() {
	*x = SaveTaskResponse{}
	mi := &file_api_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTaskResponse) ProtoMessage() {}

func (x *SaveTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTaskResponse.ProtoReflect.Descriptor instead.
func (*SaveTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{15}
}

func (x *SaveTaskResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteTask
type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_api_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_api_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{17}
}

// RecomputeSchedule
type RecomputeScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       int64                  `protobuf:"varint,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecomputeScheduleRequest) Reset() {
	*x = RecomputeScheduleRequest{}
	mi := &file_api_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecomputeScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecomputeScheduleRequest) ProtoMessage() {}

func (x *RecomputeScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecomputeScheduleRequest.ProtoReflect.Descriptor instead.
func (*RecomputeScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{18}
}

func (x *RecomputeScheduleRequest) GetProfile() int64 {
	if x != nil {
		return x.Profile
	}
	return 0
}

type RecomputeScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecomputeScheduleResponse) Reset() {
	*x = RecomputeScheduleResponse{}
	mi := &file_api_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecomputeScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecomputeScheduleResponse) ProtoMessage() {}

func (x *RecomputeScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecomputeScheduleResponse.ProtoReflect.Descriptor instead.
func (*RecomputeScheduleResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{19}
}

// ListScheduledTasks
type ListScheduledTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     int64                  `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Timescale     int64                  `protobuf:"varint,2,opt,name=timescale,proto3" json:"timescale,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledTasksRequest) Reset() {
	*x = ListScheduledTasksRequest{}
	mi := &file_api_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledTasksRequest) ProtoMessage() {}

func (x *ListScheduledTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledTasksRequest.ProtoReflect.Descriptor instead.
func (*ListScheduledTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{20}
}

func (x *ListScheduledTasksRequest) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *ListScheduledTasksRequest) GetTimescale() int64 {
	if x != nil {
		return x.Timescale
	}
	return 0
}

func (x *ListScheduledTasksRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ListScheduledTasksRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type ListScheduledTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledTasksResponse) Reset() {
	*x = ListScheduledTasksResponse{}
	mi := &file_api_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledTasksResponse) ProtoMessage() {}

func (x *ListScheduledTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledTasksResponse.ProtoReflect.Descriptor instead.
func (*ListScheduledTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{21}
}

func (x *ListScheduledTasksResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ListPossibleRelatives
type ListPossibleRelativesRequest struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Type          ListPossibleRelativesRequest_RelativeType `protobuf:"varint,1,opt,name=type,proto3,enum=ListPossibleRelativesRequest_RelativeType" json:"type,omitempty"`
	TaskId        int64                                     `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPossibleRelativesRequest) Reset() {
	*x = ListPossibleRelativesRequest{}
	mi := &file_api_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPossibleRelativesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPossibleRelativesRequest) ProtoMessage() {}

func (x *ListPossibleRelativesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPossibleRelativesRequest.ProtoReflect.Descriptor instead.
func (*ListPossibleRelativesRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{22}
}

func (x *ListPossibleRelativesRequest) GetType() ListPossibleRelativesRequest_RelativeType {
	if x != nil {
		return x.Type
	}
	return ListPossibleRelativesRequest_PARENT
}

func (x *ListPossibleRelativesRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type ListPossibleRelativesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPossibleRelativesResponse) Reset() {
	*x = ListPossibleRelativesResponse{}
	mi := &file_api_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPossibleRelativesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPossibleRelativesResponse) ProtoMessage() {}

func (x *ListPossibleRelativesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPossibleRelativesResponse.ProtoReflect.Descriptor instead.
func (*ListPossibleRelativesResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{23}
}

func (x *ListPossibleRelativesResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_api_api_proto protoreflect.FileDescriptor

const file_api_api_proto_rawDesc = "" +
	"\n" +
	"\rapi/api.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"+\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8d\x01\n" +
	"\x04PERT\x12+\n" +
	"\x03pes\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x03pes\x12+\n" +
	"\x03exp\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03exp\x12+\n" +
	"\x03opt\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03opt\"\x8e\x01\n" +
	"\bDurState\x12\x19\n" +
	"\x04pert\x18\x01 \x01(\v2\x05.PERTR\x04pert\x12;\n" +
	"\bdeadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bdeadline\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x03 \x01(\x03R\ttotalCostB\v\n" +
	"\t_deadline\"\xb2\x01\n" +
	"\x13ChildrenConfigState\x12\x12\n" +
	"\x04desc\x18\x01 \x01(\tR\x04desc\x12;\n" +
	"\bdeadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bdeadline\x88\x01\x01\x12\x19\n" +
	"\bexp_cost\x18\x03 \x01(\x03R\aexpCost\x12\"\n" +
	"\bchildren\x18\x04 \x03(\v2\x06.EntryR\bchildrenB\v\n" +
	"\t_deadline\"\xc2\x03\n" +
	"\tTaskState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x12\x1c\n" +
	"\ttimescale\x18\x03 \x01(\x03R\ttimescale\x121\n" +
	"\fduration_cfg\x18\x04 \x01(\v2\t.DurStateH\x00R\vdurationCfg\x88\x01\x01\x129\n" +
	"\rchildren_cfgs\x18\x05 \x03(\v2\x14.ChildrenConfigStateR\fchildrenCfgs\x12 \n" +
	"\aprereqs\x18\x06 \x03(\v2\x06.EntryR\aprereqs\x12\"\n" +
	"\bpostreqs\x18\a \x03(\v2\x06.EntryR\bpostreqs\x12#\n" +
	"\x06parent\x18\b \x01(\v2\x06.EntryH\x01R\x06parent\x88\x01\x01\x125\n" +
	"\x05start\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x05start\x88\x01\x01\x121\n" +
	"\x03end\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x03end\x88\x01\x01B\x0f\n" +
	"\r_duration_cfgB\t\n" +
	"\a_parentB\b\n" +
	"\x06_startB\x06\n" +
	"\x04_end\"\xdd\x01\n" +
	"\x14CreateProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12D\n" +
	"\x10atomic_timescale\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0fatomicTimescale\x12A\n" +
	"\x0euniverse_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\runiverseStart\x12(\n" +
	"\x10gen_pert_choices\x18\x04 \x01(\x03R\x0egenPertChoices\"\x17\n" +
	"\x15CreateProfileResponse\"\xfa\x01\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12D\n" +
	"\x10atomic_timescale\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0fatomicTimescale\x12A\n" +
	"\x0euniverse_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\runiverseStart\x12-\n" +
	"\x10gen_pert_choices\x18\x05 \x01(\x03H\x00R\x0egenPertChoices\x88\x01\x01B\x13\n" +
	"\x11_gen_pert_choices\"\x15\n" +
	"\x13ListProfilesRequest\":\n" +
	"\x14ListProfilesResponse\x12\"\n" +
	"\aentries\x18\x01 \x03(\v2\b.ProfileR\aentries\"&\n" +
	"\x14RemoveProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x17\n" +
	"\x15RemoveProfileResponse\"!\n" +
	"\x0fReadTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"4\n" +
	"\x10ReadTaskResponse\x12 \n" +
	"\x05state\x18\x01 \x01(\v2\n" +
	".TaskStateR\x05state\"n\n" +
	"\x0fSaveTaskRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\x03R\tprofileId\x12 \n" +
	"\x05state\x18\x03 \x01(\v2\n" +
	".TaskStateR\x05stateB\x05\n" +
	"\x03_id\"\"\n" +
	"\x10SaveTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteTaskResponse\"4\n" +
	"\x18RecomputeScheduleRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\x03R\aprofile\"\x1b\n" +
	"\x19RecomputeScheduleResponse\"\xb8\x01\n" +
	"\x19ListScheduledTasksRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\x03R\tprofileId\x12\x1c\n" +
	"\ttimescale\x18\x02 \x01(\x03R\ttimescale\x120\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\">\n" +
	"\x1aListScheduledTasksResponse\x12 \n" +
	"\aentries\x18\x01 \x03(\v2\x06.EntryR\aentries\"\xb7\x01\n" +
	"\x1cListPossibleRelativesRequest\x12>\n" +
	"\x04type\x18\x01 \x01(\x0e2*.ListPossibleRelativesRequest.RelativeTypeR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\">\n" +
	"\fRelativeType\x12\n" +
	"\n" +
	"\x06PARENT\x10\x00\x12\t\n" +
	"\x05CHILD\x10\x01\x12\n" +
	"\n" +
	"\x06PREREQ\x10\x02\x12\v\n" +
	"\aPOSTREQ\x10\x03\"A\n" +
	"\x1dListPossibleRelativesResponse\x12 \n" +
	"\aentries\x18\x01 \x03(\v2\x06.EntryR\aentries2\xce\x04\n" +
	"\x03API\x12;\n" +
	"\fListProfiles\x12\x14.ListProfilesRequest\x1a\x15.ListProfilesResponse\x12>\n" +
	"\rCreateProfile\x12\x15.CreateProfileRequest\x1a\x16.CreateProfileResponse\x12>\n" +
	"\rRemoveProfile\x12\x15.RemoveProfileRequest\x1a\x16.RemoveProfileResponse\x12/\n" +
	"\bReadTask\x12\x10.ReadTaskRequest\x1a\x11.ReadTaskResponse\x12/\n" +
	"\bSaveTask\x12\x10.SaveTaskRequest\x1a\x11.SaveTaskResponse\x125\n" +
	"\n" +
	"DeleteTask\x12\x12.DeleteTaskRequest\x1a\x13.DeleteTaskResponse\x12V\n" +
	"\x15ListPossibleRelatives\x12\x1d.ListPossibleRelativesRequest\x1a\x1e.ListPossibleRelativesResponse\x12J\n" +
	"\x11RecomputeSchedule\x12\x19.RecomputeScheduleRequest\x1a\x1a.RecomputeScheduleResponse\x12M\n" +
	"\x12ListScheduledTasks\x12\x1a.ListScheduledTasksRequest\x1a\x1b.ListScheduledTasksResponseB\x1aB\bApiProtoP\x01Z\finternal/apib\x06proto3"

var (
	file_api_api_proto_rawDescOnce sync.Once
	file_api_api_proto_rawDescData []byte
)

func file_api_api_proto_rawDescGZIP() []byte {
	file_api_api_proto_rawDescOnce.Do(func() {
		file_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)))
	})
	return file_api_api_proto_rawDescData
}

var file_api_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_api_proto_goTypes = []any{
	(ListPossibleRelativesRequest_RelativeType)(0), // 0: ListPossibleRelativesRequest.RelativeType
	(*Entry)(nil),                         // 1: Entry
	(*PERT)(nil),                          // 2: PERT
	(*DurState)(nil),                      // 3: DurState
	(*ChildrenConfigState)(nil),           // 4: ChildrenConfigState
	(*TaskState)(nil),                     // 5: TaskState
	(*CreateProfileRequest)(nil),          // 6: CreateProfileRequest
	(*CreateProfileResponse)(nil),         // 7: CreateProfileResponse
	(*Profile)(nil),                       // 8: Profile
	(*ListProfilesRequest)(nil),           // 9: ListProfilesRequest
	(*ListProfilesResponse)(nil),          // 10: ListProfilesResponse
	(*RemoveProfileRequest)(nil),          // 11: RemoveProfileRequest
	(*RemoveProfileResponse)(nil),         // 12: RemoveProfileResponse
	(*ReadTaskRequest)(nil),               // 13: ReadTaskRequest
	(*ReadTaskResponse)(nil),              // 14: ReadTaskResponse
	(*SaveTaskRequest)(nil),               // 15: SaveTaskRequest
	(*SaveTaskResponse)(nil),              // 16: SaveTaskResponse
	(*DeleteTaskRequest)(nil),             // 17: DeleteTaskRequest
	(*DeleteTaskResponse)(nil),            // 18: DeleteTaskResponse
	(*RecomputeScheduleRequest)(nil),      // 19: RecomputeScheduleRequest
	(*RecomputeScheduleResponse)(nil),     // 20: RecomputeScheduleResponse
	(*ListScheduledTasksRequest)(nil),     // 21: ListScheduledTasksRequest
	(*ListScheduledTasksResponse)(nil),    // 22: ListScheduledTasksResponse
	(*ListPossibleRelativesRequest)(nil),  // 23: ListPossibleRelativesRequest
	(*ListPossibleRelativesResponse)(nil), // 24: ListPossibleRelativesResponse
	(*durationpb.Duration)(nil),           // 25: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),         // 26: google.protobuf.Timestamp
}
var file_api_api_proto_depIdxs = []int32{
	25, // 0: PERT.pes:type_name -> google.protobuf.Duration
	25, // 1: PERT.exp:type_name -> google.protobuf.Duration
	25, // 2: PERT.opt:type_name -> google.protobuf.Duration
	2,  // 3: DurState.pert:type_name -> PERT
	26, // 4: DurState.deadline:type_name -> google.protobuf.Timestamp
	26, // 5: ChildrenConfigState.deadline:type_name -> google.protobuf.Timestamp
	1,  // 6: ChildrenConfigState.children:type_name -> Entry
	3,  // 7: TaskState.duration_cfg:type_name -> DurState
	4,  // 8: TaskState.children_cfgs:type_name -> ChildrenConfigState
	1,  // 9: TaskState.prereqs:type_name -> Entry
	1,  // 10: TaskState.postreqs:type_name -> Entry
	1,  // 11: TaskState.parent:type_name -> Entry
	26, // 12: TaskState.start:type_name -> google.protobuf.Timestamp
	26, // 13: TaskState.end:type_name -> google.protobuf.Timestamp
	25, // 14: CreateProfileRequest.atomic_timescale:type_name -> google.protobuf.Duration
	26, // 15: CreateProfileRequest.universe_start:type_name -> google.protobuf.Timestamp
	25, // 16: Profile.atomic_timescale:type_name -> google.protobuf.Duration
	26, // 17: Profile.universe_start:type_name -> google.protobuf.Timestamp
	8,  // 18: ListProfilesResponse.entries:type_name -> Profile
	5,  // 19: ReadTaskResponse.state:type_name -> TaskState
	5,  // 20: SaveTaskRequest.state:type_name -> TaskState
	26, // 21: ListScheduledTasksRequest.start:type_name -> google.protobuf.Timestamp
	26, // 22: ListScheduledTasksRequest.end:type_name -> google.protobuf.Timestamp
	1,  // 23: ListScheduledTasksResponse.entries:type_name -> Entry
	0,  // 24: ListPossibleRelativesRequest.type:type_name -> ListPossibleRelativesRequest.RelativeType
	1,  // 25: ListPossibleRelativesResponse.entries:type_name -> Entry
	9,  // 26: API.ListProfiles:input_type -> ListProfilesRequest
	6,  // 27: API.CreateProfile:input_type -> CreateProfileRequest
	11, // 28: API.RemoveProfile:input_type -> RemoveProfileRequest
	13, // 29: API.ReadTask:input_type -> ReadTaskRequest
	15, // 30: API.SaveTask:input_type -> SaveTaskRequest
	17, // 31: API.DeleteTask:input_type -> DeleteTaskRequest
	23, // 32: API.ListPossibleRelatives:input_type -> ListPossibleRelativesRequest
	19, // 33: API.RecomputeSchedule:input_type -> RecomputeScheduleRequest
	21, // 34: API.ListScheduledTasks:input_type -> ListScheduledTasksRequest
	10, // 35: API.ListProfiles:output_type -> ListProfilesResponse
	7,  // 36: API.CreateProfile:output_type -> CreateProfileResponse
	12, // 37: API.RemoveProfile:output_type -> RemoveProfileResponse
	14, // 38: API.ReadTask:output_type -> ReadTaskResponse
	16, // 39: API.SaveTask:output_type -> SaveTaskResponse
	18, // 40: API.DeleteTask:output_type -> DeleteTaskResponse
	24, // 41: API.ListPossibleRelatives:output_type -> ListPossibleRelativesResponse
	20, // 42: API.RecomputeSchedule:output_type -> RecomputeScheduleResponse
	22, // 43: API.ListScheduledTasks:output_type -> ListScheduledTasksResponse
	35, // [35:44] is the sub-list for method output_type
	26, // [26:35] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	file_api_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_api_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_api_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_api_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_api_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		EnumInfos:         file_api_api_proto_enumTypes,
		MessageInfos:      file_api_api_proto_msgTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}
