// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/types.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRelativesRequest_RelativeType int32

const (
	ListRelativesRequest_PARENT  ListRelativesRequest_RelativeType = 0
	ListRelativesRequest_CHILD   ListRelativesRequest_RelativeType = 1
	ListRelativesRequest_PREREQ  ListRelativesRequest_RelativeType = 2
	ListRelativesRequest_POSTREQ ListRelativesRequest_RelativeType = 3
)

// Enum value maps for ListRelativesRequest_RelativeType.
var (
	ListRelativesRequest_RelativeType_name = map[int32]string{
		0: "PARENT",
		1: "CHILD",
		2: "PREREQ",
		3: "POSTREQ",
	}
	ListRelativesRequest_RelativeType_value = map[string]int32{
		"PARENT":  0,
		"CHILD":   1,
		"PREREQ":  2,
		"POSTREQ": 3,
	}
)

func (x ListRelativesRequest_RelativeType) Enum() *ListRelativesRequest_RelativeType {
	p := new(ListRelativesRequest_RelativeType)
	*p = x
	return p
}

func (x ListRelativesRequest_RelativeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListRelativesRequest_RelativeType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_types_proto_enumTypes[0].Descriptor()
}

func (ListRelativesRequest_RelativeType) Type() protoreflect.EnumType {
	return &file_api_types_proto_enumTypes[0]
}

func (x ListRelativesRequest_RelativeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListRelativesRequest_RelativeType.Descriptor instead.
func (ListRelativesRequest_RelativeType) EnumDescriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{14, 0}
}

type DurState struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Pes      int64                  `protobuf:"varint,1,opt,name=pes,proto3" json:"pes,omitempty"`
	Exp      int64                  `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	Opt      int64                  `protobuf:"varint,3,opt,name=opt,proto3" json:"opt,omitempty"`
	Deadline *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	// zero if null
	TotalCost     int64 `protobuf:"varint,5,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurState) Reset() {
	*x = DurState{}
	mi := &file_api_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurState) ProtoMessage() {}

func (x *DurState) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurState.ProtoReflect.Descriptor instead.
func (*DurState) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{0}
}

func (x *DurState) GetPes() int64 {
	if x != nil {
		return x.Pes
	}
	return 0
}

func (x *DurState) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *DurState) GetOpt() int64 {
	if x != nil {
		return x.Opt
	}
	return 0
}

func (x *DurState) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *DurState) GetTotalCost() int64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

type ChildrenConfigState struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Desc     string                 `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	Deadline *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	// zero if null
	ExpCost       int64   `protobuf:"varint,3,opt,name=exp_cost,json=expCost,proto3" json:"exp_cost,omitempty"`
	Children      []int64 `protobuf:"varint,4,rep,packed,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildrenConfigState) Reset() {
	*x = ChildrenConfigState{}
	mi := &file_api_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildrenConfigState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildrenConfigState) ProtoMessage() {}

func (x *ChildrenConfigState) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildrenConfigState.ProtoReflect.Descriptor instead.
func (*ChildrenConfigState) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{1}
}

func (x *ChildrenConfigState) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ChildrenConfigState) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *ChildrenConfigState) GetExpCost() int64 {
	if x != nil {
		return x.ExpCost
	}
	return 0
}

func (x *ChildrenConfigState) GetChildren() []int64 {
	if x != nil {
		return x.Children
	}
	return nil
}

type TaskState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Timescale     int64                  `protobuf:"varint,3,opt,name=timescale,proto3" json:"timescale,omitempty"`
	DurationCfg   *DurState              `protobuf:"bytes,4,opt,name=duration_cfg,json=durationCfg,proto3" json:"duration_cfg,omitempty"`
	ChildrenCfgs  []*ChildrenConfigState `protobuf:"bytes,5,rep,name=children_cfgs,json=childrenCfgs,proto3" json:"children_cfgs,omitempty"`
	Prereqs       []int64                `protobuf:"varint,6,rep,packed,name=prereqs,proto3" json:"prereqs,omitempty"`
	Postreqs      []int64                `protobuf:"varint,7,rep,packed,name=postreqs,proto3" json:"postreqs,omitempty"`
	Parent        *int64                 `protobuf:"varint,8,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskState) Reset() {
	*x = TaskState{}
	mi := &file_api_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskState) ProtoMessage() {}

func (x *TaskState) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskState.ProtoReflect.Descriptor instead.
func (*TaskState) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{2}
}

func (x *TaskState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskState) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *TaskState) GetTimescale() int64 {
	if x != nil {
		return x.Timescale
	}
	return 0
}

func (x *TaskState) GetDurationCfg() *DurState {
	if x != nil {
		return x.DurationCfg
	}
	return nil
}

func (x *TaskState) GetChildrenCfgs() []*ChildrenConfigState {
	if x != nil {
		return x.ChildrenCfgs
	}
	return nil
}

func (x *TaskState) GetPrereqs() []int64 {
	if x != nil {
		return x.Prereqs
	}
	return nil
}

func (x *TaskState) GetPostreqs() []int64 {
	if x != nil {
		return x.Postreqs
	}
	return nil
}

func (x *TaskState) GetParent() int64 {
	if x != nil && x.Parent != nil {
		return *x.Parent
	}
	return 0
}

type TaskEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEntry) Reset() {
	*x = TaskEntry{}
	mi := &file_api_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEntry) ProtoMessage() {}

func (x *TaskEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEntry.ProtoReflect.Descriptor instead.
func (*TaskEntry) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{3}
}

func (x *TaskEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ReadTask
type ReadTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaskRequest) Reset() {
	*x = ReadTaskRequest{}
	mi := &file_api_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaskRequest) ProtoMessage() {}

func (x *ReadTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaskRequest.ProtoReflect.Descriptor instead.
func (*ReadTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{4}
}

func (x *ReadTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *TaskState             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaskResponse) Reset() {
	*x = ReadTaskResponse{}
	mi := &file_api_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaskResponse) ProtoMessage() {}

func (x *ReadTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaskResponse.ProtoReflect.Descriptor instead.
func (*ReadTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{5}
}

func (x *ReadTaskResponse) GetState() *TaskState {
	if x != nil {
		return x.State
	}
	return nil
}

// CreateTask
type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *TaskState             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_api_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTaskRequest) GetState() *TaskState {
	if x != nil {
		return x.State
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_api_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{7}
}

// UpdateTask
type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State         *TaskState             `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_api_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTaskRequest) GetState() *TaskState {
	if x != nil {
		return x.State
	}
	return nil
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_api_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{9}
}

// DeleteTask
type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_api_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_api_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{11}
}

// ListScheduledTasks
type ListScheduledTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledTasksRequest) Reset() {
	*x = ListScheduledTasksRequest{}
	mi := &file_api_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledTasksRequest) ProtoMessage() {}

func (x *ListScheduledTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledTasksRequest.ProtoReflect.Descriptor instead.
func (*ListScheduledTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{12}
}

func (x *ListScheduledTasksRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ListScheduledTasksRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type ListScheduledTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*TaskEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledTasksResponse) Reset() {
	*x = ListScheduledTasksResponse{}
	mi := &file_api_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledTasksResponse) ProtoMessage() {}

func (x *ListScheduledTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledTasksResponse.ProtoReflect.Descriptor instead.
func (*ListScheduledTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{13}
}

func (x *ListScheduledTasksResponse) GetEntries() []*TaskEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ListRelatives
type ListRelativesRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Type          ListRelativesRequest_RelativeType `protobuf:"varint,1,opt,name=type,proto3,enum=ListRelativesRequest_RelativeType" json:"type,omitempty"`
	TaskId        int64                             `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelativesRequest) Reset() {
	*x = ListRelativesRequest{}
	mi := &file_api_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelativesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelativesRequest) ProtoMessage() {}

func (x *ListRelativesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelativesRequest.ProtoReflect.Descriptor instead.
func (*ListRelativesRequest) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{14}
}

func (x *ListRelativesRequest) GetType() ListRelativesRequest_RelativeType {
	if x != nil {
		return x.Type
	}
	return ListRelativesRequest_PARENT
}

func (x *ListRelativesRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type ListRelativesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*TaskEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelativesResponse) Reset() {
	*x = ListRelativesResponse{}
	mi := &file_api_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelativesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelativesResponse) ProtoMessage() {}

func (x *ListRelativesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelativesResponse.ProtoReflect.Descriptor instead.
func (*ListRelativesResponse) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{15}
}

func (x *ListRelativesResponse) GetEntries() []*TaskEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ProgressUpdate
type ProgressUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetTaskId  int64                  `protobuf:"varint,1,opt,name=target_task_id,json=targetTaskId,proto3" json:"target_task_id,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdateRequest) Reset() {
	*x = ProgressUpdateRequest{}
	mi := &file_api_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdateRequest) ProtoMessage() {}

func (x *ProgressUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProgressUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{16}
}

func (x *ProgressUpdateRequest) GetTargetTaskId() int64 {
	if x != nil {
		return x.TargetTaskId
	}
	return 0
}

func (x *ProgressUpdateRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ProgressUpdateRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type ProgressUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdateResponse) Reset() {
	*x = ProgressUpdateResponse{}
	mi := &file_api_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdateResponse) ProtoMessage() {}

func (x *ProgressUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdateResponse.ProtoReflect.Descriptor instead.
func (*ProgressUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_types_proto_rawDescGZIP(), []int{17}
}

var File_api_types_proto protoreflect.FileDescriptor

const file_api_types_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x01\n" +
	"\bDurState\x12\x10\n" +
	"\x03pes\x18\x01 \x01(\x03R\x03pes\x12\x10\n" +
	"\x03exp\x18\x02 \x01(\x03R\x03exp\x12\x10\n" +
	"\x03opt\x18\x03 \x01(\x03R\x03opt\x12;\n" +
	"\bdeadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bdeadline\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x05 \x01(\x03R\ttotalCostB\v\n" +
	"\t_deadline\"\xaa\x01\n" +
	"\x13ChildrenConfigState\x12\x12\n" +
	"\x04desc\x18\x01 \x01(\tR\x04desc\x12;\n" +
	"\bdeadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bdeadline\x88\x01\x01\x12\x19\n" +
	"\bexp_cost\x18\x03 \x01(\x03R\aexpCost\x12\x1a\n" +
	"\bchildren\x18\x04 \x03(\x03R\bchildrenB\v\n" +
	"\t_deadline\"\x98\x02\n" +
	"\tTaskState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x12\x1c\n" +
	"\ttimescale\x18\x03 \x01(\x03R\ttimescale\x12,\n" +
	"\fduration_cfg\x18\x04 \x01(\v2\t.DurStateR\vdurationCfg\x129\n" +
	"\rchildren_cfgs\x18\x05 \x03(\v2\x14.ChildrenConfigStateR\fchildrenCfgs\x12\x18\n" +
	"\aprereqs\x18\x06 \x03(\x03R\aprereqs\x12\x1a\n" +
	"\bpostreqs\x18\a \x03(\x03R\bpostreqs\x12\x1b\n" +
	"\x06parent\x18\b \x01(\x03H\x00R\x06parent\x88\x01\x01B\t\n" +
	"\a_parent\"/\n" +
	"\tTaskEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"!\n" +
	"\x0fReadTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"4\n" +
	"\x10ReadTaskResponse\x12 \n" +
	"\x05state\x18\x01 \x01(\v2\n" +
	".TaskStateR\x05state\"5\n" +
	"\x11CreateTaskRequest\x12 \n" +
	"\x05state\x18\x01 \x01(\v2\n" +
	".TaskStateR\x05state\"\x14\n" +
	"\x12CreateTaskResponse\"E\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\x05state\x18\x02 \x01(\v2\n" +
	".TaskStateR\x05state\"\x14\n" +
	"\x12UpdateTaskResponse\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteTaskResponse\"{\n" +
	"\x19ListScheduledTasksRequest\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"B\n" +
	"\x1aListScheduledTasksResponse\x12$\n" +
	"\aentries\x18\x01 \x03(\v2\n" +
	".TaskEntryR\aentries\"\xa7\x01\n" +
	"\x14ListRelativesRequest\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".ListRelativesRequest.RelativeTypeR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\">\n" +
	"\fRelativeType\x12\n" +
	"\n" +
	"\x06PARENT\x10\x00\x12\t\n" +
	"\x05CHILD\x10\x01\x12\n" +
	"\n" +
	"\x06PREREQ\x10\x02\x12\v\n" +
	"\aPOSTREQ\x10\x03\"=\n" +
	"\x15ListRelativesResponse\x12$\n" +
	"\aentries\x18\x01 \x03(\v2\n" +
	".TaskEntryR\aentries\"\x9d\x01\n" +
	"\x15ProgressUpdateRequest\x12$\n" +
	"\x0etarget_task_id\x18\x01 \x01(\x03R\ftargetTaskId\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\x18\n" +
	"\x16ProgressUpdateResponse2\xea\x02\n" +
	"\x03API\x12/\n" +
	"\bReadTask\x12\x10.ReadTaskRequest\x1a\x11.ReadTaskResponse\x125\n" +
	"\n" +
	"CreateTask\x12\x12.CreateTaskRequest\x1a\x13.CreateTaskResponse\x125\n" +
	"\n" +
	"UpdateTask\x12\x12.UpdateTaskRequest\x1a\x13.UpdateTaskResponse\x125\n" +
	"\n" +
	"DeleteTask\x12\x12.DeleteTaskRequest\x1a\x13.DeleteTaskResponse\x12M\n" +
	"\x12ListScheduledTasks\x12\x1a.ListScheduledTasksRequest\x1a\x1b.ListScheduledTasksResponse\x12>\n" +
	"\rListRelatives\x12\x15.ListRelativesRequest\x1a\x16.ListRelativesResponseB\x1cB\n" +
	"TypesProtoP\x01Z\finternal/apib\x06proto3"

var (
	file_api_types_proto_rawDescOnce sync.Once
	file_api_types_proto_rawDescData []byte
)

func file_api_types_proto_rawDescGZIP() []byte {
	file_api_types_proto_rawDescOnce.Do(func() {
		file_api_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_types_proto_rawDesc), len(file_api_types_proto_rawDesc)))
	})
	return file_api_types_proto_rawDescData
}

var file_api_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_types_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_types_proto_goTypes = []any{
	(ListRelativesRequest_RelativeType)(0), // 0: ListRelativesRequest.RelativeType
	(*DurState)(nil),                       // 1: DurState
	(*ChildrenConfigState)(nil),            // 2: ChildrenConfigState
	(*TaskState)(nil),                      // 3: TaskState
	(*TaskEntry)(nil),                      // 4: TaskEntry
	(*ReadTaskRequest)(nil),                // 5: ReadTaskRequest
	(*ReadTaskResponse)(nil),               // 6: ReadTaskResponse
	(*CreateTaskRequest)(nil),              // 7: CreateTaskRequest
	(*CreateTaskResponse)(nil),             // 8: CreateTaskResponse
	(*UpdateTaskRequest)(nil),              // 9: UpdateTaskRequest
	(*UpdateTaskResponse)(nil),             // 10: UpdateTaskResponse
	(*DeleteTaskRequest)(nil),              // 11: DeleteTaskRequest
	(*DeleteTaskResponse)(nil),             // 12: DeleteTaskResponse
	(*ListScheduledTasksRequest)(nil),      // 13: ListScheduledTasksRequest
	(*ListScheduledTasksResponse)(nil),     // 14: ListScheduledTasksResponse
	(*ListRelativesRequest)(nil),           // 15: ListRelativesRequest
	(*ListRelativesResponse)(nil),          // 16: ListRelativesResponse
	(*ProgressUpdateRequest)(nil),          // 17: ProgressUpdateRequest
	(*ProgressUpdateResponse)(nil),         // 18: ProgressUpdateResponse
	(*timestamppb.Timestamp)(nil),          // 19: google.protobuf.Timestamp
}
var file_api_types_proto_depIdxs = []int32{
	19, // 0: DurState.deadline:type_name -> google.protobuf.Timestamp
	19, // 1: ChildrenConfigState.deadline:type_name -> google.protobuf.Timestamp
	1,  // 2: TaskState.duration_cfg:type_name -> DurState
	2,  // 3: TaskState.children_cfgs:type_name -> ChildrenConfigState
	3,  // 4: ReadTaskResponse.state:type_name -> TaskState
	3,  // 5: CreateTaskRequest.state:type_name -> TaskState
	3,  // 6: UpdateTaskRequest.state:type_name -> TaskState
	19, // 7: ListScheduledTasksRequest.start:type_name -> google.protobuf.Timestamp
	19, // 8: ListScheduledTasksRequest.end:type_name -> google.protobuf.Timestamp
	4,  // 9: ListScheduledTasksResponse.entries:type_name -> TaskEntry
	0,  // 10: ListRelativesRequest.type:type_name -> ListRelativesRequest.RelativeType
	4,  // 11: ListRelativesResponse.entries:type_name -> TaskEntry
	19, // 12: ProgressUpdateRequest.start:type_name -> google.protobuf.Timestamp
	19, // 13: ProgressUpdateRequest.end:type_name -> google.protobuf.Timestamp
	5,  // 14: API.ReadTask:input_type -> ReadTaskRequest
	7,  // 15: API.CreateTask:input_type -> CreateTaskRequest
	9,  // 16: API.UpdateTask:input_type -> UpdateTaskRequest
	11, // 17: API.DeleteTask:input_type -> DeleteTaskRequest
	13, // 18: API.ListScheduledTasks:input_type -> ListScheduledTasksRequest
	15, // 19: API.ListRelatives:input_type -> ListRelativesRequest
	6,  // 20: API.ReadTask:output_type -> ReadTaskResponse
	8,  // 21: API.CreateTask:output_type -> CreateTaskResponse
	10, // 22: API.UpdateTask:output_type -> UpdateTaskResponse
	12, // 23: API.DeleteTask:output_type -> DeleteTaskResponse
	14, // 24: API.ListScheduledTasks:output_type -> ListScheduledTasksResponse
	16, // 25: API.ListRelatives:output_type -> ListRelativesResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_types_proto_init() }
func file_api_types_proto_init() {
	if File_api_types_proto != nil {
		return
	}
	file_api_types_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_types_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_types_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_types_proto_rawDesc), len(file_api_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_types_proto_goTypes,
		DependencyIndexes: file_api_types_proto_depIdxs,
		EnumInfos:         file_api_types_proto_enumTypes,
		MessageInfos:      file_api_types_proto_msgTypes,
	}.Build()
	File_api_types_proto = out.File
	file_api_types_proto_goTypes = nil
	file_api_types_proto_depIdxs = nil
}
