// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: solverpb/service.proto

package solverpb

import (
	commonpb "cpsat-scheduler/internal/proto/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SolveStatus int32

const (
	SolveStatus_FEASIBLE      SolveStatus = 0
	SolveStatus_INFEASIBLE    SolveStatus = 1
	SolveStatus_MODEL_INVALID SolveStatus = 2
	SolveStatus_OPTIMAL       SolveStatus = 3
	SolveStatus_UNKNOWN       SolveStatus = 4
)

// Enum value maps for SolveStatus.
var (
	SolveStatus_name = map[int32]string{
		0: "FEASIBLE",
		1: "INFEASIBLE",
		2: "MODEL_INVALID",
		3: "OPTIMAL",
		4: "UNKNOWN",
	}
	SolveStatus_value = map[string]int32{
		"FEASIBLE":      0,
		"INFEASIBLE":    1,
		"MODEL_INVALID": 2,
		"OPTIMAL":       3,
		"UNKNOWN":       4,
	}
)

func (x SolveStatus) Enum() *SolveStatus {
	p := new(SolveStatus)
	*p = x
	return p
}

func (x SolveStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SolveStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_solverpb_service_proto_enumTypes[0].Descriptor()
}

func (SolveStatus) Type() protoreflect.EnumType {
	return &file_solverpb_service_proto_enumTypes[0]
}

func (x SolveStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SolveStatus.Descriptor instead.
func (SolveStatus) EnumDescriptor() ([]byte, []int) {
	return file_solverpb_service_proto_rawDescGZIP(), []int{0}
}

type CostInterval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *commonpb.AtomicUnit   `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *commonpb.AtomicUnit   `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Cost          int64                  `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostInterval) Reset() {
	*x = CostInterval{}
	mi := &file_solverpb_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostInterval) ProtoMessage() {}

func (x *CostInterval) ProtoReflect() protoreflect.Message {
	mi := &file_solverpb_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostInterval.ProtoReflect.Descriptor instead.
func (*CostInterval) Descriptor() ([]byte, []int) {
	return file_solverpb_service_proto_rawDescGZIP(), []int{0}
}

func (x *CostInterval) GetStart() *commonpb.AtomicUnit {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *CostInterval) GetEnd() *commonpb.AtomicUnit {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *CostInterval) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type DurConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intervals     []*CostInterval        `protobuf:"bytes,1,rep,name=intervals,proto3" json:"intervals,omitempty"`
	Duration      *commonpb.AtomicUnit   `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurConfig) Reset() {
	*x = DurConfig{}
	mi := &file_solverpb_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurConfig) ProtoMessage() {}

func (x *DurConfig) ProtoReflect() protoreflect.Message {
	mi := &file_solverpb_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurConfig.ProtoReflect.Descriptor instead.
func (*DurConfig) Descriptor() ([]byte, []int) {
	return file_solverpb_service_proto_rawDescGZIP(), []int{1}
}

func (x *DurConfig) GetIntervals() []*CostInterval {
	if x != nil {
		return x.Intervals
	}
	return nil
}

func (x *DurConfig) GetDuration() *commonpb.AtomicUnit {
	if x != nil {
		return x.Duration
	}
	return nil
}

type ChildrenConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intervals     []*CostInterval        `protobuf:"bytes,1,rep,name=intervals,proto3" json:"intervals,omitempty"`
	Children      []int64                `protobuf:"varint,2,rep,packed,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildrenConfig) Reset() {
	*x = ChildrenConfig{}
	mi := &file_solverpb_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildrenConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildrenConfig) ProtoMessage() {}

func (x *ChildrenConfig) ProtoReflect() protoreflect.Message {
	mi := &file_solverpb_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildrenConfig.ProtoReflect.Descriptor instead.
func (*ChildrenConfig) Descriptor() ([]byte, []int) {
	return file_solverpb_service_proto_rawDescGZIP(), []int{2}
}

func (x *ChildrenConfig) GetIntervals() []*CostInterval {
	if x != nil {
		return x.Intervals
	}
	return nil
}

func (x *ChildrenConfig) GetChildren() []int64 {
	if x != nil {
		return x.Children
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Unit          *commonpb.AtomicUnit   `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Start         *commonpb.AtomicUnit   `protobuf:"bytes,3,opt,name=start,proto3,oneof" json:"start,omitempty"`
	End           *commonpb.AtomicUnit   `protobuf:"bytes,4,opt,name=end,proto3,oneof" json:"end,omitempty"`
	Prereqs       []int64                `protobuf:"varint,5,rep,packed,name=prereqs,proto3" json:"prereqs,omitempty"`
	DurCfgs       []*DurConfig           `protobuf:"bytes,6,rep,name=dur_cfgs,json=durCfgs,proto3" json:"dur_cfgs,omitempty"`
	ChildrenCfgs  []*ChildrenConfig      `protobuf:"bytes,7,rep,name=children_cfgs,json=childrenCfgs,proto3" json:"children_cfgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_solverpb_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_solverpb_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_solverpb_service_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetUnit() *commonpb.AtomicUnit {
	if x != nil {
		return x.Unit
	}
	return nil
}

func (x *Task) GetStart() *commonpb.AtomicUnit {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Task) GetEnd() *commonpb.AtomicUnit {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *Task) GetPrereqs() []int64 {
	if x != nil {
		return x.Prereqs
	}
	return nil
}

func (x *Task) GetDurCfgs() []*DurConfig {
	if x != nil {
		return x.DurCfgs
	}
	return nil
}

func (x *Task) GetChildrenCfgs() []*ChildrenConfig {
	if x != nil {
		return x.ChildrenCfgs
	}
	return nil
}

type SolvedTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the id passed in the request
	Id    int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Start *commonpb.AtomicUnit `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	// the config selected
	//
	// Types that are valid to be assigned to Config:
	//
	//	*SolvedTask_DurIdx
	//	*SolvedTask_ChildrenIdx
	Config isSolvedTask_Config `protobuf_oneof:"config"`
	// the cost used
	Cost          int64                `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Duration      *commonpb.AtomicUnit `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	End           *commonpb.AtomicUnit `protobuf:"bytes,7,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolvedTask) Reset() {
	*x = SolvedTask{}
	mi := &file_solverpb_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolvedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolvedTask) ProtoMessage() {}

func (x *SolvedTask) ProtoReflect() protoreflect.Message {
	mi := &file_solverpb_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolvedTask.ProtoReflect.Descriptor instead.
func (*SolvedTask) Descriptor() ([]byte, []int) {
	return file_solverpb_service_proto_rawDescGZIP(), []int{4}
}

func (x *SolvedTask) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SolvedTask) GetStart() *commonpb.AtomicUnit {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *SolvedTask) GetConfig() isSolvedTask_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SolvedTask) GetDurIdx() int64 {
	if x != nil {
		if x, ok := x.Config.(*SolvedTask_DurIdx); ok {
			return x.DurIdx
		}
	}
	return 0
}

func (x *SolvedTask) GetChildrenIdx() int64 {
	if x != nil {
		if x, ok := x.Config.(*SolvedTask_ChildrenIdx); ok {
			return x.ChildrenIdx
		}
	}
	return 0
}

func (x *SolvedTask) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *SolvedTask) GetDuration() *commonpb.AtomicUnit {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *SolvedTask) GetEnd() *commonpb.AtomicUnit {
	if x != nil {
		return x.End
	}
	return nil
}

type isSolvedTask_Config interface {
	isSolvedTask_Config()
}

type SolvedTask_DurIdx struct {
	// the id of the duration config
	DurIdx int64 `protobuf:"varint,3,opt,name=dur_idx,json=durIdx,proto3,oneof"`
}

type SolvedTask_ChildrenIdx struct {
	// the id of the children config
	ChildrenIdx int64 `protobuf:"varint,4,opt,name=children_idx,json=childrenIdx,proto3,oneof"`
}

func (*SolvedTask_DurIdx) isSolvedTask_Config() {}

func (*SolvedTask_ChildrenIdx) isSolvedTask_Config() {}

// Solve
type SolveRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Horizon       *commonpb.AtomicInterval `protobuf:"bytes,1,opt,name=horizon,proto3" json:"horizon,omitempty"`
	Tasks         []*Task                  `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolveRequest) Reset() {
	*x = SolveRequest{}
	mi := &file_solverpb_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolveRequest) ProtoMessage() {}

func (x *SolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_solverpb_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolveRequest.ProtoReflect.Descriptor instead.
func (*SolveRequest) Descriptor() ([]byte, []int) {
	return file_solverpb_service_proto_rawDescGZIP(), []int{5}
}

func (x *SolveRequest) GetHorizon() *commonpb.AtomicInterval {
	if x != nil {
		return x.Horizon
	}
	return nil
}

func (x *SolveRequest) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type SolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        SolveStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=SolveStatus" json:"status,omitempty"`
	Score         int64                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Solution      []*SolvedTask          `protobuf:"bytes,3,rep,name=solution,proto3" json:"solution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolveResponse) Reset() {
	*x = SolveResponse{}
	mi := &file_solverpb_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolveResponse) ProtoMessage() {}

func (x *SolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_solverpb_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolveResponse.ProtoReflect.Descriptor instead.
func (*SolveResponse) Descriptor() ([]byte, []int) {
	return file_solverpb_service_proto_rawDescGZIP(), []int{6}
}

func (x *SolveResponse) GetStatus() SolveStatus {
	if x != nil {
		return x.Status
	}
	return SolveStatus_FEASIBLE
}

func (x *SolveResponse) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SolveResponse) GetSolution() []*SolvedTask {
	if x != nil {
		return x.Solution
	}
	return nil
}

var File_solverpb_service_proto protoreflect.FileDescriptor

const file_solverpb_service_proto_rawDesc = "" +
	"\n" +
	"\x16solverpb/service.proto\x1a\x14commonpb/types.proto\"d\n" +
	"\fCostInterval\x12!\n" +
	"\x05start\x18\x01 \x01(\v2\v.AtomicUnitR\x05start\x12\x1d\n" +
	"\x03end\x18\x02 \x01(\v2\v.AtomicUnitR\x03end\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x03R\x04cost\"a\n" +
	"\tDurConfig\x12+\n" +
	"\tintervals\x18\x01 \x03(\v2\r.CostIntervalR\tintervals\x12'\n" +
	"\bduration\x18\x02 \x01(\v2\v.AtomicUnitR\bduration\"Y\n" +
	"\x0eChildrenConfig\x12+\n" +
	"\tintervals\x18\x01 \x03(\v2\r.CostIntervalR\tintervals\x12\x1a\n" +
	"\bchildren\x18\x02 \x03(\x03R\bchildren\"\x8c\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\x04unit\x18\x02 \x01(\v2\v.AtomicUnitR\x04unit\x12&\n" +
	"\x05start\x18\x03 \x01(\v2\v.AtomicUnitH\x00R\x05start\x88\x01\x01\x12\"\n" +
	"\x03end\x18\x04 \x01(\v2\v.AtomicUnitH\x01R\x03end\x88\x01\x01\x12\x18\n" +
	"\aprereqs\x18\x05 \x03(\x03R\aprereqs\x12%\n" +
	"\bdur_cfgs\x18\x06 \x03(\v2\n" +
	".DurConfigR\adurCfgs\x124\n" +
	"\rchildren_cfgs\x18\a \x03(\v2\x0f.ChildrenConfigR\fchildrenCfgsB\b\n" +
	"\x06_startB\x06\n" +
	"\x04_end\"\xe5\x01\n" +
	"\n" +
	"SolvedTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\x05start\x18\x02 \x01(\v2\v.AtomicUnitR\x05start\x12\x19\n" +
	"\adur_idx\x18\x03 \x01(\x03H\x00R\x06durIdx\x12#\n" +
	"\fchildren_idx\x18\x04 \x01(\x03H\x00R\vchildrenIdx\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x03R\x04cost\x12'\n" +
	"\bduration\x18\x06 \x01(\v2\v.AtomicUnitR\bduration\x12\x1d\n" +
	"\x03end\x18\a \x01(\v2\v.AtomicUnitR\x03endB\b\n" +
	"\x06config\"V\n" +
	"\fSolveRequest\x12)\n" +
	"\ahorizon\x18\x01 \x01(\v2\x0f.AtomicIntervalR\ahorizon\x12\x1b\n" +
	"\x05tasks\x18\x02 \x03(\v2\x05.TaskR\x05tasks\"t\n" +
	"\rSolveResponse\x12$\n" +
	"\x06status\x18\x01 \x01(\x0e2\f.SolveStatusR\x06status\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x03R\x05score\x12'\n" +
	"\bsolution\x18\x03 \x03(\v2\v.SolvedTaskR\bsolution*X\n" +
	"\vSolveStatus\x12\f\n" +
	"\bFEASIBLE\x10\x00\x12\x0e\n" +
	"\n" +
	"INFEASIBLE\x10\x01\x12\x11\n" +
	"\rMODEL_INVALID\x10\x02\x12\v\n" +
	"\aOPTIMAL\x10\x03\x12\v\n" +
	"\aUNKNOWN\x10\x0420\n" +
	"\x06Solver\x12&\n" +
	"\x05Solve\x12\r.SolveRequest\x1a\x0e.SolveResponseB9B\fServiceProtoP\x01Z'cpsat-scheduler/internal/proto/solverpbb\x06proto3"

var (
	file_solverpb_service_proto_rawDescOnce sync.Once
	file_solverpb_service_proto_rawDescData []byte
)

func file_solverpb_service_proto_rawDescGZIP() []byte {
	file_solverpb_service_proto_rawDescOnce.Do(func() {
		file_solverpb_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_solverpb_service_proto_rawDesc), len(file_solverpb_service_proto_rawDesc)))
	})
	return file_solverpb_service_proto_rawDescData
}

var file_solverpb_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_solverpb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_solverpb_service_proto_goTypes = []any{
	(SolveStatus)(0),                // 0: SolveStatus
	(*CostInterval)(nil),            // 1: CostInterval
	(*DurConfig)(nil),               // 2: DurConfig
	(*ChildrenConfig)(nil),          // 3: ChildrenConfig
	(*Task)(nil),                    // 4: Task
	(*SolvedTask)(nil),              // 5: SolvedTask
	(*SolveRequest)(nil),            // 6: SolveRequest
	(*SolveResponse)(nil),           // 7: SolveResponse
	(*commonpb.AtomicUnit)(nil),     // 8: AtomicUnit
	(*commonpb.AtomicInterval)(nil), // 9: AtomicInterval
}
var file_solverpb_service_proto_depIdxs = []int32{
	8,  // 0: CostInterval.start:type_name -> AtomicUnit
	8,  // 1: CostInterval.end:type_name -> AtomicUnit
	1,  // 2: DurConfig.intervals:type_name -> CostInterval
	8,  // 3: DurConfig.duration:type_name -> AtomicUnit
	1,  // 4: ChildrenConfig.intervals:type_name -> CostInterval
	8,  // 5: Task.unit:type_name -> AtomicUnit
	8,  // 6: Task.start:type_name -> AtomicUnit
	8,  // 7: Task.end:type_name -> AtomicUnit
	2,  // 8: Task.dur_cfgs:type_name -> DurConfig
	3,  // 9: Task.children_cfgs:type_name -> ChildrenConfig
	8,  // 10: SolvedTask.start:type_name -> AtomicUnit
	8,  // 11: SolvedTask.duration:type_name -> AtomicUnit
	8,  // 12: SolvedTask.end:type_name -> AtomicUnit
	9,  // 13: SolveRequest.horizon:type_name -> AtomicInterval
	4,  // 14: SolveRequest.tasks:type_name -> Task
	0,  // 15: SolveResponse.status:type_name -> SolveStatus
	5,  // 16: SolveResponse.solution:type_name -> SolvedTask
	6,  // 17: Solver.Solve:input_type -> SolveRequest
	7,  // 18: Solver.Solve:output_type -> SolveResponse
	18, // [18:19] is the sub-list for method output_type
	17, // [17:18] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_solverpb_service_proto_init() }
func file_solverpb_service_proto_init() {
	if File_solverpb_service_proto != nil {
		return
	}
	file_solverpb_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_solverpb_service_proto_msgTypes[4].OneofWrappers = []any{
		(*SolvedTask_DurIdx)(nil),
		(*SolvedTask_ChildrenIdx)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_solverpb_service_proto_rawDesc), len(file_solverpb_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_solverpb_service_proto_goTypes,
		DependencyIndexes: file_solverpb_service_proto_depIdxs,
		EnumInfos:         file_solverpb_service_proto_enumTypes,
		MessageInfos:      file_solverpb_service_proto_msgTypes,
	}.Build()
	File_solverpb_service_proto = out.File
	file_solverpb_service_proto_goTypes = nil
	file_solverpb_service_proto_depIdxs = nil
}
