// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: apipb/api.proto

package apipb

import (
	commonpb "cpsat-scheduler/internal/proto/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPossibleRelativesRequest_RelativeType int32

const (
	ListPossibleRelativesRequest_PARENT  ListPossibleRelativesRequest_RelativeType = 0
	ListPossibleRelativesRequest_CHILD   ListPossibleRelativesRequest_RelativeType = 1
	ListPossibleRelativesRequest_PREREQ  ListPossibleRelativesRequest_RelativeType = 2
	ListPossibleRelativesRequest_POSTREQ ListPossibleRelativesRequest_RelativeType = 3
)

// Enum value maps for ListPossibleRelativesRequest_RelativeType.
var (
	ListPossibleRelativesRequest_RelativeType_name = map[int32]string{
		0: "PARENT",
		1: "CHILD",
		2: "PREREQ",
		3: "POSTREQ",
	}
	ListPossibleRelativesRequest_RelativeType_value = map[string]int32{
		"PARENT":  0,
		"CHILD":   1,
		"PREREQ":  2,
		"POSTREQ": 3,
	}
)

func (x ListPossibleRelativesRequest_RelativeType) Enum() *ListPossibleRelativesRequest_RelativeType {
	p := new(ListPossibleRelativesRequest_RelativeType)
	*p = x
	return p
}

func (x ListPossibleRelativesRequest_RelativeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListPossibleRelativesRequest_RelativeType) Descriptor() protoreflect.EnumDescriptor {
	return file_apipb_api_proto_enumTypes[0].Descriptor()
}

func (ListPossibleRelativesRequest_RelativeType) Type() protoreflect.EnumType {
	return &file_apipb_api_proto_enumTypes[0]
}

func (x ListPossibleRelativesRequest_RelativeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListPossibleRelativesRequest_RelativeType.Descriptor instead.
func (ListPossibleRelativesRequest_RelativeType) EnumDescriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{21, 0}
}

type PERT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pes           *durationpb.Duration   `protobuf:"bytes,1,opt,name=pes,proto3" json:"pes,omitempty"`
	Exp           *durationpb.Duration   `protobuf:"bytes,2,opt,name=exp,proto3" json:"exp,omitempty"`
	Opt           *durationpb.Duration   `protobuf:"bytes,3,opt,name=opt,proto3" json:"opt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PERT) Reset() {
	*x = PERT{}
	mi := &file_apipb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PERT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PERT) ProtoMessage() {}

func (x *PERT) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PERT.ProtoReflect.Descriptor instead.
func (*PERT) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{0}
}

func (x *PERT) GetPes() *durationpb.Duration {
	if x != nil {
		return x.Pes
	}
	return nil
}

func (x *PERT) GetExp() *durationpb.Duration {
	if x != nil {
		return x.Exp
	}
	return nil
}

func (x *PERT) GetOpt() *durationpb.Duration {
	if x != nil {
		return x.Opt
	}
	return nil
}

type DurState struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Pert     *PERT                  `protobuf:"bytes,1,opt,name=pert,proto3" json:"pert,omitempty"`
	Deadline *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	// zero if null
	TotalCost     int64 `protobuf:"varint,3,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurState) Reset() {
	*x = DurState{}
	mi := &file_apipb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurState) ProtoMessage() {}

func (x *DurState) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurState.ProtoReflect.Descriptor instead.
func (*DurState) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{1}
}

func (x *DurState) GetPert() *PERT {
	if x != nil {
		return x.Pert
	}
	return nil
}

func (x *DurState) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *DurState) GetTotalCost() int64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

type ChildrenConfigState struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Desc     string                 `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	Deadline *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	// zero if null
	ExpCost       int64             `protobuf:"varint,3,opt,name=exp_cost,json=expCost,proto3" json:"exp_cost,omitempty"`
	Children      []*commonpb.Entry `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildrenConfigState) Reset() {
	*x = ChildrenConfigState{}
	mi := &file_apipb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildrenConfigState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildrenConfigState) ProtoMessage() {}

func (x *ChildrenConfigState) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildrenConfigState.ProtoReflect.Descriptor instead.
func (*ChildrenConfigState) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{2}
}

func (x *ChildrenConfigState) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ChildrenConfigState) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *ChildrenConfigState) GetExpCost() int64 {
	if x != nil {
		return x.ExpCost
	}
	return 0
}

func (x *ChildrenConfigState) GetChildren() []*commonpb.Entry {
	if x != nil {
		return x.Children
	}
	return nil
}

type TaskState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Timescale     int64                  `protobuf:"varint,3,opt,name=timescale,proto3" json:"timescale,omitempty"`
	DurationCfg   *DurState              `protobuf:"bytes,4,opt,name=duration_cfg,json=durationCfg,proto3,oneof" json:"duration_cfg,omitempty"`
	ChildrenCfgs  []*ChildrenConfigState `protobuf:"bytes,5,rep,name=children_cfgs,json=childrenCfgs,proto3" json:"children_cfgs,omitempty"`
	Prereqs       []*commonpb.Entry      `protobuf:"bytes,6,rep,name=prereqs,proto3" json:"prereqs,omitempty"`
	Postreqs      []*commonpb.Entry      `protobuf:"bytes,7,rep,name=postreqs,proto3" json:"postreqs,omitempty"`
	Parent        *commonpb.Entry        `protobuf:"bytes,8,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start,proto3,oneof" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=end,proto3,oneof" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskState) Reset() {
	*x = TaskState{}
	mi := &file_apipb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskState) ProtoMessage() {}

func (x *TaskState) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskState.ProtoReflect.Descriptor instead.
func (*TaskState) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{3}
}

func (x *TaskState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskState) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *TaskState) GetTimescale() int64 {
	if x != nil {
		return x.Timescale
	}
	return 0
}

func (x *TaskState) GetDurationCfg() *DurState {
	if x != nil {
		return x.DurationCfg
	}
	return nil
}

func (x *TaskState) GetChildrenCfgs() []*ChildrenConfigState {
	if x != nil {
		return x.ChildrenCfgs
	}
	return nil
}

func (x *TaskState) GetPrereqs() []*commonpb.Entry {
	if x != nil {
		return x.Prereqs
	}
	return nil
}

func (x *TaskState) GetPostreqs() []*commonpb.Entry {
	if x != nil {
		return x.Postreqs
	}
	return nil
}

func (x *TaskState) GetParent() *commonpb.Entry {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *TaskState) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TaskState) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

// CreateProfile
type CreateProfileRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AtomicTimescale *durationpb.Duration   `protobuf:"bytes,2,opt,name=atomic_timescale,json=atomicTimescale,proto3" json:"atomic_timescale,omitempty"`
	UniverseStart   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=universe_start,json=universeStart,proto3" json:"universe_start,omitempty"`
	GenPertChoices  int64                  `protobuf:"varint,4,opt,name=gen_pert_choices,json=genPertChoices,proto3" json:"gen_pert_choices,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_apipb_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProfileRequest) GetAtomicTimescale() *durationpb.Duration {
	if x != nil {
		return x.AtomicTimescale
	}
	return nil
}

func (x *CreateProfileRequest) GetUniverseStart() *timestamppb.Timestamp {
	if x != nil {
		return x.UniverseStart
	}
	return nil
}

func (x *CreateProfileRequest) GetGenPertChoices() int64 {
	if x != nil {
		return x.GenPertChoices
	}
	return 0
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_apipb_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{5}
}

type Profile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AtomicTimescale *durationpb.Duration   `protobuf:"bytes,3,opt,name=atomic_timescale,json=atomicTimescale,proto3" json:"atomic_timescale,omitempty"`
	UniverseStart   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=universe_start,json=universeStart,proto3" json:"universe_start,omitempty"`
	GenPertChoices  *int64                 `protobuf:"varint,5,opt,name=gen_pert_choices,json=genPertChoices,proto3,oneof" json:"gen_pert_choices,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_apipb_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{6}
}

func (x *Profile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetAtomicTimescale() *durationpb.Duration {
	if x != nil {
		return x.AtomicTimescale
	}
	return nil
}

func (x *Profile) GetUniverseStart() *timestamppb.Timestamp {
	if x != nil {
		return x.UniverseStart
	}
	return nil
}

func (x *Profile) GetGenPertChoices() int64 {
	if x != nil && x.GenPertChoices != nil {
		return *x.GenPertChoices
	}
	return 0
}

// ListProfiles
type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_apipb_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{7}
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Profile             `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_apipb_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{8}
}

func (x *ListProfilesResponse) GetEntries() []*Profile {
	if x != nil {
		return x.Entries
	}
	return nil
}

// RemoveProfile
type RemoveProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProfileRequest) Reset() {
	*x = RemoveProfileRequest{}
	mi := &file_apipb_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProfileRequest) ProtoMessage() {}

func (x *RemoveProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProfileRequest.ProtoReflect.Descriptor instead.
func (*RemoveProfileRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveProfileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProfileResponse) Reset() {
	*x = RemoveProfileResponse{}
	mi := &file_apipb_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProfileResponse) ProtoMessage() {}

func (x *RemoveProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProfileResponse.ProtoReflect.Descriptor instead.
func (*RemoveProfileResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{10}
}

// ReadTask
type ReadTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaskRequest) Reset() {
	*x = ReadTaskRequest{}
	mi := &file_apipb_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaskRequest) ProtoMessage() {}

func (x *ReadTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaskRequest.ProtoReflect.Descriptor instead.
func (*ReadTaskRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{11}
}

func (x *ReadTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *TaskState             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaskResponse) Reset() {
	*x = ReadTaskResponse{}
	mi := &file_apipb_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaskResponse) ProtoMessage() {}

func (x *ReadTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaskResponse.ProtoReflect.Descriptor instead.
func (*ReadTaskResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{12}
}

func (x *ReadTaskResponse) GetState() *TaskState {
	if x != nil {
		return x.State
	}
	return nil
}

// SaveTask
type SaveTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	ProfileId     int64                  `protobuf:"varint,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	State         *TaskState             `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTaskRequest) Reset() {
	*x = SaveTaskRequest{}
	mi := &file_apipb_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTaskRequest) ProtoMessage() {}

func (x *SaveTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTaskRequest.ProtoReflect.Descriptor instead.
func (*SaveTaskRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{13}
}

func (x *SaveTaskRequest) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SaveTaskRequest) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *SaveTaskRequest) GetState() *TaskState {
	if x != nil {
		return x.State
	}
	return nil
}

type SaveTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTaskResponse) Reset() {
	*x = SaveTaskResponse{}
	mi := &file_apipb_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTaskResponse) ProtoMessage() {}

func (x *SaveTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTaskResponse.ProtoReflect.Descriptor instead.
func (*SaveTaskResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{14}
}

func (x *SaveTaskResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteTask
type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_apipb_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_apipb_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{16}
}

// RecomputeSchedule
type RecomputeScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       int64                  `protobuf:"varint,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Horizon       *commonpb.Interval     `protobuf:"bytes,2,opt,name=horizon,proto3" json:"horizon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecomputeScheduleRequest) Reset() {
	*x = RecomputeScheduleRequest{}
	mi := &file_apipb_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecomputeScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecomputeScheduleRequest) ProtoMessage() {}

func (x *RecomputeScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecomputeScheduleRequest.ProtoReflect.Descriptor instead.
func (*RecomputeScheduleRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{17}
}

func (x *RecomputeScheduleRequest) GetProfile() int64 {
	if x != nil {
		return x.Profile
	}
	return 0
}

func (x *RecomputeScheduleRequest) GetHorizon() *commonpb.Interval {
	if x != nil {
		return x.Horizon
	}
	return nil
}

type RecomputeScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecomputeScheduleResponse) Reset() {
	*x = RecomputeScheduleResponse{}
	mi := &file_apipb_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecomputeScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecomputeScheduleResponse) ProtoMessage() {}

func (x *RecomputeScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecomputeScheduleResponse.ProtoReflect.Descriptor instead.
func (*RecomputeScheduleResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{18}
}

// ListScheduledTasks
type ListScheduledTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     int64                  `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Timescale     *int64                 `protobuf:"varint,2,opt,name=timescale,proto3,oneof" json:"timescale,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledTasksRequest) Reset() {
	*x = ListScheduledTasksRequest{}
	mi := &file_apipb_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledTasksRequest) ProtoMessage() {}

func (x *ListScheduledTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledTasksRequest.ProtoReflect.Descriptor instead.
func (*ListScheduledTasksRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{19}
}

func (x *ListScheduledTasksRequest) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *ListScheduledTasksRequest) GetTimescale() int64 {
	if x != nil && x.Timescale != nil {
		return *x.Timescale
	}
	return 0
}

func (x *ListScheduledTasksRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ListScheduledTasksRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type ListScheduledTasksResponse struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	Entries       []*ListScheduledTasksResponse_ScheduledTask `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledTasksResponse) Reset() {
	*x = ListScheduledTasksResponse{}
	mi := &file_apipb_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledTasksResponse) ProtoMessage() {}

func (x *ListScheduledTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledTasksResponse.ProtoReflect.Descriptor instead.
func (*ListScheduledTasksResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{20}
}

func (x *ListScheduledTasksResponse) GetEntries() []*ListScheduledTasksResponse_ScheduledTask {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ListPossibleRelatives
type ListPossibleRelativesRequest struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Type          ListPossibleRelativesRequest_RelativeType `protobuf:"varint,1,opt,name=type,proto3,enum=ListPossibleRelativesRequest_RelativeType" json:"type,omitempty"`
	TaskId        int64                                     `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPossibleRelativesRequest) Reset() {
	*x = ListPossibleRelativesRequest{}
	mi := &file_apipb_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPossibleRelativesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPossibleRelativesRequest) ProtoMessage() {}

func (x *ListPossibleRelativesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPossibleRelativesRequest.ProtoReflect.Descriptor instead.
func (*ListPossibleRelativesRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{21}
}

func (x *ListPossibleRelativesRequest) GetType() ListPossibleRelativesRequest_RelativeType {
	if x != nil {
		return x.Type
	}
	return ListPossibleRelativesRequest_PARENT
}

func (x *ListPossibleRelativesRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type ListPossibleRelativesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*commonpb.Entry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPossibleRelativesResponse) Reset() {
	*x = ListPossibleRelativesResponse{}
	mi := &file_apipb_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPossibleRelativesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPossibleRelativesResponse) ProtoMessage() {}

func (x *ListPossibleRelativesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPossibleRelativesResponse.ProtoReflect.Descriptor instead.
func (*ListPossibleRelativesResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{22}
}

func (x *ListPossibleRelativesResponse) GetEntries() []*commonpb.Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ListProgressUpdates
type ListProgressUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       int64                  `protobuf:"varint,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProgressUpdatesRequest) Reset() {
	*x = ListProgressUpdatesRequest{}
	mi := &file_apipb_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProgressUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProgressUpdatesRequest) ProtoMessage() {}

func (x *ListProgressUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProgressUpdatesRequest.ProtoReflect.Descriptor instead.
func (*ListProgressUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{23}
}

func (x *ListProgressUpdatesRequest) GetProfile() int64 {
	if x != nil {
		return x.Profile
	}
	return 0
}

func (x *ListProgressUpdatesRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ListProgressUpdatesRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type ListProgressUpdatesResponse struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Logs          []*ListProgressUpdatesResponse_ProgressLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProgressUpdatesResponse) Reset() {
	*x = ListProgressUpdatesResponse{}
	mi := &file_apipb_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProgressUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProgressUpdatesResponse) ProtoMessage() {}

func (x *ListProgressUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProgressUpdatesResponse.ProtoReflect.Descriptor instead.
func (*ListProgressUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{24}
}

func (x *ListProgressUpdatesResponse) GetLogs() []*ListProgressUpdatesResponse_ProgressLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

// ProgressUpdate
type ProgressUpdateRequest struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Profile       int64                                `protobuf:"varint,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Time          *timestamppb.Timestamp               `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Desc          string                               `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Updates       []*ProgressUpdateRequest_UpdatedTask `protobuf:"bytes,4,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdateRequest) Reset() {
	*x = ProgressUpdateRequest{}
	mi := &file_apipb_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdateRequest) ProtoMessage() {}

func (x *ProgressUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProgressUpdateRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{25}
}

func (x *ProgressUpdateRequest) GetProfile() int64 {
	if x != nil {
		return x.Profile
	}
	return 0
}

func (x *ProgressUpdateRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ProgressUpdateRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ProgressUpdateRequest) GetUpdates() []*ProgressUpdateRequest_UpdatedTask {
	if x != nil {
		return x.Updates
	}
	return nil
}

type ProgressUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdateResponse) Reset() {
	*x = ProgressUpdateResponse{}
	mi := &file_apipb_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdateResponse) ProtoMessage() {}

func (x *ProgressUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdateResponse.ProtoReflect.Descriptor instead.
func (*ProgressUpdateResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{26}
}

func (x *ProgressUpdateResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// EditProgressLog
type EditProgressLogRequest struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Id            int64                                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Time          *timestamppb.Timestamp                `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Desc          string                                `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Updates       []*EditProgressLogRequest_UpdatedTask `protobuf:"bytes,4,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditProgressLogRequest) Reset() {
	*x = EditProgressLogRequest{}
	mi := &file_apipb_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditProgressLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditProgressLogRequest) ProtoMessage() {}

func (x *EditProgressLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditProgressLogRequest.ProtoReflect.Descriptor instead.
func (*EditProgressLogRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{27}
}

func (x *EditProgressLogRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditProgressLogRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *EditProgressLogRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *EditProgressLogRequest) GetUpdates() []*EditProgressLogRequest_UpdatedTask {
	if x != nil {
		return x.Updates
	}
	return nil
}

type EditProgressLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditProgressLogResponse) Reset() {
	*x = EditProgressLogResponse{}
	mi := &file_apipb_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditProgressLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditProgressLogResponse) ProtoMessage() {}

func (x *EditProgressLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditProgressLogResponse.ProtoReflect.Descriptor instead.
func (*EditProgressLogResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{28}
}

// DeleteProgressLog
type DeleteProgressLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProgressLogRequest) Reset() {
	*x = DeleteProgressLogRequest{}
	mi := &file_apipb_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProgressLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProgressLogRequest) ProtoMessage() {}

func (x *DeleteProgressLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProgressLogRequest.ProtoReflect.Descriptor instead.
func (*DeleteProgressLogRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteProgressLogRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProgressLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProgressLogResponse) Reset() {
	*x = DeleteProgressLogResponse{}
	mi := &file_apipb_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProgressLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProgressLogResponse) ProtoMessage() {}

func (x *DeleteProgressLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProgressLogResponse.ProtoReflect.Descriptor instead.
func (*DeleteProgressLogResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{30}
}

// GetLastCheckpoint
type GetLastCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       int64                  `protobuf:"varint,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastCheckpointRequest) Reset() {
	*x = GetLastCheckpointRequest{}
	mi := &file_apipb_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastCheckpointRequest) ProtoMessage() {}

func (x *GetLastCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastCheckpointRequest.ProtoReflect.Descriptor instead.
func (*GetLastCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{31}
}

func (x *GetLastCheckpointRequest) GetProfile() int64 {
	if x != nil {
		return x.Profile
	}
	return 0
}

type GetLastCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3,oneof" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastCheckpointResponse) Reset() {
	*x = GetLastCheckpointResponse{}
	mi := &file_apipb_api_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastCheckpointResponse) ProtoMessage() {}

func (x *GetLastCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastCheckpointResponse.ProtoReflect.Descriptor instead.
func (*GetLastCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{32}
}

func (x *GetLastCheckpointResponse) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       int64                  `protobuf:"varint,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_apipb_api_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{33}
}

func (x *Event) GetProfile() int64 {
	if x != nil {
		return x.Profile
	}
	return 0
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Event) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Event) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

// CreateEvent
type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         []*Event               `protobuf:"bytes,1,rep,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_apipb_api_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{34}
}

func (x *CreateEventRequest) GetEvent() []*Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_apipb_api_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{35}
}

// ReadEvent
type ReadEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadEventRequest) Reset() {
	*x = ReadEventRequest{}
	mi := &file_apipb_api_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEventRequest) ProtoMessage() {}

func (x *ReadEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEventRequest.ProtoReflect.Descriptor instead.
func (*ReadEventRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{36}
}

func (x *ReadEventRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadEventResponse) Reset() {
	*x = ReadEventResponse{}
	mi := &file_apipb_api_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEventResponse) ProtoMessage() {}

func (x *ReadEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEventResponse.ProtoReflect.Descriptor instead.
func (*ReadEventResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{37}
}

func (x *ReadEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// UpdateEvent
type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Event         *Event                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_apipb_api_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{38}
}

func (x *UpdateEventRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_apipb_api_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{39}
}

// ListEvent
type ListEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       int64                  `protobuf:"varint,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventRequest) Reset() {
	*x = ListEventRequest{}
	mi := &file_apipb_api_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventRequest) ProtoMessage() {}

func (x *ListEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventRequest.ProtoReflect.Descriptor instead.
func (*ListEventRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{40}
}

func (x *ListEventRequest) GetProfile() int64 {
	if x != nil {
		return x.Profile
	}
	return 0
}

type ListEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*commonpb.Entry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventResponse) Reset() {
	*x = ListEventResponse{}
	mi := &file_apipb_api_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventResponse) ProtoMessage() {}

func (x *ListEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventResponse.ProtoReflect.Descriptor instead.
func (*ListEventResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{41}
}

func (x *ListEventResponse) GetEntries() []*commonpb.Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// RemoveEvent
type RemoveEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEventRequest) Reset() {
	*x = RemoveEventRequest{}
	mi := &file_apipb_api_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEventRequest) ProtoMessage() {}

func (x *RemoveEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEventRequest.ProtoReflect.Descriptor instead.
func (*RemoveEventRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{42}
}

func (x *RemoveEventRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEventResponse) Reset() {
	*x = RemoveEventResponse{}
	mi := &file_apipb_api_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEventResponse) ProtoMessage() {}

func (x *RemoveEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEventResponse.ProtoReflect.Descriptor instead.
func (*RemoveEventResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{43}
}

// ListTasks
type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       int64                  `protobuf:"varint,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_apipb_api_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{44}
}

func (x *ListTasksRequest) GetProfile() int64 {
	if x != nil {
		return x.Profile
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*commonpb.Entry      `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_apipb_api_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{45}
}

func (x *ListTasksResponse) GetTasks() []*commonpb.Entry {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ListScheduledTasksResponse_ScheduledTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledTasksResponse_ScheduledTask) Reset() {
	*x = ListScheduledTasksResponse_ScheduledTask{}
	mi := &file_apipb_api_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledTasksResponse_ScheduledTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledTasksResponse_ScheduledTask) ProtoMessage() {}

func (x *ListScheduledTasksResponse_ScheduledTask) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledTasksResponse_ScheduledTask.ProtoReflect.Descriptor instead.
func (*ListScheduledTasksResponse_ScheduledTask) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{20, 0}
}

func (x *ListScheduledTasksResponse_ScheduledTask) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListScheduledTasksResponse_ScheduledTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListScheduledTasksResponse_ScheduledTask) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type ListProgressUpdatesResponse_ProgressLog struct {
	state         protoimpl.MessageState                                 `protogen:"open.v1"`
	Id            int64                                                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Time          *timestamppb.Timestamp                                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Desc          string                                                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Updates       []*ListProgressUpdatesResponse_ProgressLog_UpdatedTask `protobuf:"bytes,4,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProgressUpdatesResponse_ProgressLog) Reset() {
	*x = ListProgressUpdatesResponse_ProgressLog{}
	mi := &file_apipb_api_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProgressUpdatesResponse_ProgressLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProgressUpdatesResponse_ProgressLog) ProtoMessage() {}

func (x *ListProgressUpdatesResponse_ProgressLog) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProgressUpdatesResponse_ProgressLog.ProtoReflect.Descriptor instead.
func (*ListProgressUpdatesResponse_ProgressLog) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{24, 0}
}

func (x *ListProgressUpdatesResponse_ProgressLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListProgressUpdatesResponse_ProgressLog) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ListProgressUpdatesResponse_ProgressLog) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ListProgressUpdatesResponse_ProgressLog) GetUpdates() []*ListProgressUpdatesResponse_ProgressLog_UpdatedTask {
	if x != nil {
		return x.Updates
	}
	return nil
}

type ListProgressUpdatesResponse_ProgressLog_UpdatedTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *commonpb.Entry        `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProgressUpdatesResponse_ProgressLog_UpdatedTask) Reset() {
	*x = ListProgressUpdatesResponse_ProgressLog_UpdatedTask{}
	mi := &file_apipb_api_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProgressUpdatesResponse_ProgressLog_UpdatedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProgressUpdatesResponse_ProgressLog_UpdatedTask) ProtoMessage() {}

func (x *ListProgressUpdatesResponse_ProgressLog_UpdatedTask) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProgressUpdatesResponse_ProgressLog_UpdatedTask.ProtoReflect.Descriptor instead.
func (*ListProgressUpdatesResponse_ProgressLog_UpdatedTask) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{24, 0, 0}
}

func (x *ListProgressUpdatesResponse_ProgressLog_UpdatedTask) GetTask() *commonpb.Entry {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *ListProgressUpdatesResponse_ProgressLog_UpdatedTask) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type ProgressUpdateRequest_UpdatedTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          int64                  `protobuf:"varint,1,opt,name=task,proto3" json:"task,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdateRequest_UpdatedTask) Reset() {
	*x = ProgressUpdateRequest_UpdatedTask{}
	mi := &file_apipb_api_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdateRequest_UpdatedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdateRequest_UpdatedTask) ProtoMessage() {}

func (x *ProgressUpdateRequest_UpdatedTask) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdateRequest_UpdatedTask.ProtoReflect.Descriptor instead.
func (*ProgressUpdateRequest_UpdatedTask) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{25, 0}
}

func (x *ProgressUpdateRequest_UpdatedTask) GetTask() int64 {
	if x != nil {
		return x.Task
	}
	return 0
}

func (x *ProgressUpdateRequest_UpdatedTask) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type EditProgressLogRequest_UpdatedTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          int64                  `protobuf:"varint,1,opt,name=task,proto3" json:"task,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditProgressLogRequest_UpdatedTask) Reset() {
	*x = EditProgressLogRequest_UpdatedTask{}
	mi := &file_apipb_api_proto_msgTypes[50]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditProgressLogRequest_UpdatedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditProgressLogRequest_UpdatedTask) ProtoMessage() {}

func (x *EditProgressLogRequest_UpdatedTask) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_api_proto_msgTypes[50]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditProgressLogRequest_UpdatedTask.ProtoReflect.Descriptor instead.
func (*EditProgressLogRequest_UpdatedTask) Descriptor() ([]byte, []int) {
	return file_apipb_api_proto_rawDescGZIP(), []int{27, 0}
}

func (x *EditProgressLogRequest_UpdatedTask) GetTask() int64 {
	if x != nil {
		return x.Task
	}
	return 0
}

func (x *EditProgressLogRequest_UpdatedTask) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_apipb_api_proto protoreflect.FileDescriptor

const file_apipb_api_proto_rawDesc = "" +
	"\n" +
	"\x0fapipb/api.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x14commonpb/types.proto\"\x8d\x01\n" +
	"\x04PERT\x12+\n" +
	"\x03pes\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x03pes\x12+\n" +
	"\x03exp\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03exp\x12+\n" +
	"\x03opt\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03opt\"\x8e\x01\n" +
	"\bDurState\x12\x19\n" +
	"\x04pert\x18\x01 \x01(\v2\x05.PERTR\x04pert\x12;\n" +
	"\bdeadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bdeadline\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x03 \x01(\x03R\ttotalCostB\v\n" +
	"\t_deadline\"\xb2\x01\n" +
	"\x13ChildrenConfigState\x12\x12\n" +
	"\x04desc\x18\x01 \x01(\tR\x04desc\x12;\n" +
	"\bdeadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bdeadline\x88\x01\x01\x12\x19\n" +
	"\bexp_cost\x18\x03 \x01(\x03R\aexpCost\x12\"\n" +
	"\bchildren\x18\x04 \x03(\v2\x06.EntryR\bchildrenB\v\n" +
	"\t_deadline\"\xc2\x03\n" +
	"\tTaskState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x12\x1c\n" +
	"\ttimescale\x18\x03 \x01(\x03R\ttimescale\x121\n" +
	"\fduration_cfg\x18\x04 \x01(\v2\t.DurStateH\x00R\vdurationCfg\x88\x01\x01\x129\n" +
	"\rchildren_cfgs\x18\x05 \x03(\v2\x14.ChildrenConfigStateR\fchildrenCfgs\x12 \n" +
	"\aprereqs\x18\x06 \x03(\v2\x06.EntryR\aprereqs\x12\"\n" +
	"\bpostreqs\x18\a \x03(\v2\x06.EntryR\bpostreqs\x12#\n" +
	"\x06parent\x18\b \x01(\v2\x06.EntryH\x01R\x06parent\x88\x01\x01\x125\n" +
	"\x05start\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x05start\x88\x01\x01\x121\n" +
	"\x03end\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x03end\x88\x01\x01B\x0f\n" +
	"\r_duration_cfgB\t\n" +
	"\a_parentB\b\n" +
	"\x06_startB\x06\n" +
	"\x04_end\"\xdd\x01\n" +
	"\x14CreateProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12D\n" +
	"\x10atomic_timescale\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0fatomicTimescale\x12A\n" +
	"\x0euniverse_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\runiverseStart\x12(\n" +
	"\x10gen_pert_choices\x18\x04 \x01(\x03R\x0egenPertChoices\"\x17\n" +
	"\x15CreateProfileResponse\"\xfa\x01\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12D\n" +
	"\x10atomic_timescale\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0fatomicTimescale\x12A\n" +
	"\x0euniverse_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\runiverseStart\x12-\n" +
	"\x10gen_pert_choices\x18\x05 \x01(\x03H\x00R\x0egenPertChoices\x88\x01\x01B\x13\n" +
	"\x11_gen_pert_choices\"\x15\n" +
	"\x13ListProfilesRequest\":\n" +
	"\x14ListProfilesResponse\x12\"\n" +
	"\aentries\x18\x01 \x03(\v2\b.ProfileR\aentries\"&\n" +
	"\x14RemoveProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x17\n" +
	"\x15RemoveProfileResponse\"!\n" +
	"\x0fReadTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"4\n" +
	"\x10ReadTaskResponse\x12 \n" +
	"\x05state\x18\x01 \x01(\v2\n" +
	".TaskStateR\x05state\"n\n" +
	"\x0fSaveTaskRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\x03R\tprofileId\x12 \n" +
	"\x05state\x18\x03 \x01(\v2\n" +
	".TaskStateR\x05stateB\x05\n" +
	"\x03_id\"\"\n" +
	"\x10SaveTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteTaskResponse\"Y\n" +
	"\x18RecomputeScheduleRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\x03R\aprofile\x12#\n" +
	"\ahorizon\x18\x02 \x01(\v2\t.IntervalR\ahorizon\"\x1b\n" +
	"\x19RecomputeScheduleResponse\"\xcb\x01\n" +
	"\x19ListScheduledTasksRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\x03R\tprofileId\x12!\n" +
	"\ttimescale\x18\x02 \x01(\x03H\x00R\ttimescale\x88\x01\x01\x120\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x03endB\f\n" +
	"\n" +
	"_timescale\"\xcd\x01\n" +
	"\x1aListScheduledTasksResponse\x12C\n" +
	"\aentries\x18\x01 \x03(\v2).ListScheduledTasksResponse.ScheduledTaskR\aentries\x1aj\n" +
	"\rScheduledTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\"\xb7\x01\n" +
	"\x1cListPossibleRelativesRequest\x12>\n" +
	"\x04type\x18\x01 \x01(\x0e2*.ListPossibleRelativesRequest.RelativeTypeR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\">\n" +
	"\fRelativeType\x12\n" +
	"\n" +
	"\x06PARENT\x10\x00\x12\t\n" +
	"\x05CHILD\x10\x01\x12\n" +
	"\n" +
	"\x06PREREQ\x10\x02\x12\v\n" +
	"\aPOSTREQ\x10\x03\"A\n" +
	"\x1dListPossibleRelativesResponse\x12 \n" +
	"\aentries\x18\x01 \x03(\v2\x06.EntryR\aentries\"\x96\x01\n" +
	"\x1aListProgressUpdatesRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\x03R\aprofile\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xce\x02\n" +
	"\x1bListProgressUpdatesResponse\x12<\n" +
	"\x04logs\x18\x01 \x03(\v2(.ListProgressUpdatesResponse.ProgressLogR\x04logs\x1a\xf0\x01\n" +
	"\vProgressLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12N\n" +
	"\aupdates\x18\x04 \x03(\v24.ListProgressUpdatesResponse.ProgressLog.UpdatedTaskR\aupdates\x1a=\n" +
	"\vUpdatedTask\x12\x1a\n" +
	"\x04task\x18\x01 \x01(\v2\x06.EntryR\x04task\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\"\xea\x01\n" +
	"\x15ProgressUpdateRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\x03R\aprofile\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12<\n" +
	"\aupdates\x18\x04 \x03(\v2\".ProgressUpdateRequest.UpdatedTaskR\aupdates\x1a5\n" +
	"\vUpdatedTask\x12\x12\n" +
	"\x04task\x18\x01 \x01(\x03R\x04task\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\"(\n" +
	"\x16ProgressUpdateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xe2\x01\n" +
	"\x16EditProgressLogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12=\n" +
	"\aupdates\x18\x04 \x03(\v2#.EditProgressLogRequest.UpdatedTaskR\aupdates\x1a5\n" +
	"\vUpdatedTask\x12\x12\n" +
	"\x04task\x18\x01 \x01(\x03R\x04task\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\"\x19\n" +
	"\x17EditProgressLogResponse\"*\n" +
	"\x18DeleteProgressLogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1b\n" +
	"\x19DeleteProgressLogResponse\"4\n" +
	"\x18GetLastCheckpointRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\x03R\aprofile\"Y\n" +
	"\x19GetLastCheckpointResponse\x123\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04time\x88\x01\x01B\a\n" +
	"\x05_time\"\xa9\x01\n" +
	"\x05Event\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\x03R\aprofile\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x120\n" +
	"\x05start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"2\n" +
	"\x12CreateEventRequest\x12\x1c\n" +
	"\x05event\x18\x01 \x03(\v2\x06.EventR\x05event\"\x15\n" +
	"\x13CreateEventResponse\"\"\n" +
	"\x10ReadEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\x11ReadEventResponse\x12\x1c\n" +
	"\x05event\x18\x01 \x01(\v2\x06.EventR\x05event\"B\n" +
	"\x12UpdateEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\x05event\x18\x02 \x01(\v2\x06.EventR\x05event\"\x15\n" +
	"\x13UpdateEventResponse\",\n" +
	"\x10ListEventRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\x03R\aprofile\"5\n" +
	"\x11ListEventResponse\x12 \n" +
	"\aentries\x18\x01 \x03(\v2\x06.EntryR\aentries\"$\n" +
	"\x12RemoveEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x15\n" +
	"\x13RemoveEventResponse\",\n" +
	"\x10ListTasksRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\x03R\aprofile\"1\n" +
	"\x11ListTasksResponse\x12\x1c\n" +
	"\x05tasks\x18\x01 \x03(\v2\x06.EntryR\x05tasks2\x8b\n" +
	"\n" +
	"\x03API\x12;\n" +
	"\fListProfiles\x12\x14.ListProfilesRequest\x1a\x15.ListProfilesResponse\x12>\n" +
	"\rCreateProfile\x12\x15.CreateProfileRequest\x1a\x16.CreateProfileResponse\x12>\n" +
	"\rRemoveProfile\x12\x15.RemoveProfileRequest\x1a\x16.RemoveProfileResponse\x122\n" +
	"\tListTasks\x12\x11.ListTasksRequest\x1a\x12.ListTasksResponse\x12/\n" +
	"\bReadTask\x12\x10.ReadTaskRequest\x1a\x11.ReadTaskResponse\x12/\n" +
	"\bSaveTask\x12\x10.SaveTaskRequest\x1a\x11.SaveTaskResponse\x125\n" +
	"\n" +
	"DeleteTask\x12\x12.DeleteTaskRequest\x1a\x13.DeleteTaskResponse\x12V\n" +
	"\x15ListPossibleRelatives\x12\x1d.ListPossibleRelativesRequest\x1a\x1e.ListPossibleRelativesResponse\x12J\n" +
	"\x11RecomputeSchedule\x12\x19.RecomputeScheduleRequest\x1a\x1a.RecomputeScheduleResponse\x12M\n" +
	"\x12ListScheduledTasks\x12\x1a.ListScheduledTasksRequest\x1a\x1b.ListScheduledTasksResponse\x12P\n" +
	"\x13ListProgressUpdates\x12\x1b.ListProgressUpdatesRequest\x1a\x1c.ListProgressUpdatesResponse\x12A\n" +
	"\x0eProgressUpdate\x12\x16.ProgressUpdateRequest\x1a\x17.ProgressUpdateResponse\x12D\n" +
	"\x0fEditProgressLog\x12\x17.EditProgressLogRequest\x1a\x18.EditProgressLogResponse\x12J\n" +
	"\x11DeleteProgressLog\x12\x19.DeleteProgressLogRequest\x1a\x1a.DeleteProgressLogResponse\x12J\n" +
	"\x11GetLastCheckpoint\x12\x19.GetLastCheckpointRequest\x1a\x1a.GetLastCheckpointResponse\x128\n" +
	"\vCreateEvent\x12\x13.CreateEventRequest\x1a\x14.CreateEventResponse\x122\n" +
	"\tReadEvent\x12\x11.ReadEventRequest\x1a\x12.ReadEventResponse\x128\n" +
	"\vUpdateEvent\x12\x13.UpdateEventRequest\x1a\x14.UpdateEventResponse\x122\n" +
	"\tListEvent\x12\x11.ListEventRequest\x1a\x12.ListEventResponse\x128\n" +
	"\vRemoveEvent\x12\x13.RemoveEventRequest\x1a\x14.RemoveEventResponseB2B\bApiProtoP\x01Z$cpsat-scheduler/internal/proto/apipbb\x06proto3"

var (
	file_apipb_api_proto_rawDescOnce sync.Once
	file_apipb_api_proto_rawDescData []byte
)

func file_apipb_api_proto_rawDescGZIP() []byte {
	file_apipb_api_proto_rawDescOnce.Do(func() {
		file_apipb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apipb_api_proto_rawDesc), len(file_apipb_api_proto_rawDesc)))
	})
	return file_apipb_api_proto_rawDescData
}

var file_apipb_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apipb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 51)
var file_apipb_api_proto_goTypes = []any{
	(ListPossibleRelativesRequest_RelativeType)(0), // 0: ListPossibleRelativesRequest.RelativeType
	(*PERT)(nil),                                                // 1: PERT
	(*DurState)(nil),                                            // 2: DurState
	(*ChildrenConfigState)(nil),                                 // 3: ChildrenConfigState
	(*TaskState)(nil),                                           // 4: TaskState
	(*CreateProfileRequest)(nil),                                // 5: CreateProfileRequest
	(*CreateProfileResponse)(nil),                               // 6: CreateProfileResponse
	(*Profile)(nil),                                             // 7: Profile
	(*ListProfilesRequest)(nil),                                 // 8: ListProfilesRequest
	(*ListProfilesResponse)(nil),                                // 9: ListProfilesResponse
	(*RemoveProfileRequest)(nil),                                // 10: RemoveProfileRequest
	(*RemoveProfileResponse)(nil),                               // 11: RemoveProfileResponse
	(*ReadTaskRequest)(nil),                                     // 12: ReadTaskRequest
	(*ReadTaskResponse)(nil),                                    // 13: ReadTaskResponse
	(*SaveTaskRequest)(nil),                                     // 14: SaveTaskRequest
	(*SaveTaskResponse)(nil),                                    // 15: SaveTaskResponse
	(*DeleteTaskRequest)(nil),                                   // 16: DeleteTaskRequest
	(*DeleteTaskResponse)(nil),                                  // 17: DeleteTaskResponse
	(*RecomputeScheduleRequest)(nil),                            // 18: RecomputeScheduleRequest
	(*RecomputeScheduleResponse)(nil),                           // 19: RecomputeScheduleResponse
	(*ListScheduledTasksRequest)(nil),                           // 20: ListScheduledTasksRequest
	(*ListScheduledTasksResponse)(nil),                          // 21: ListScheduledTasksResponse
	(*ListPossibleRelativesRequest)(nil),                        // 22: ListPossibleRelativesRequest
	(*ListPossibleRelativesResponse)(nil),                       // 23: ListPossibleRelativesResponse
	(*ListProgressUpdatesRequest)(nil),                          // 24: ListProgressUpdatesRequest
	(*ListProgressUpdatesResponse)(nil),                         // 25: ListProgressUpdatesResponse
	(*ProgressUpdateRequest)(nil),                               // 26: ProgressUpdateRequest
	(*ProgressUpdateResponse)(nil),                              // 27: ProgressUpdateResponse
	(*EditProgressLogRequest)(nil),                              // 28: EditProgressLogRequest
	(*EditProgressLogResponse)(nil),                             // 29: EditProgressLogResponse
	(*DeleteProgressLogRequest)(nil),                            // 30: DeleteProgressLogRequest
	(*DeleteProgressLogResponse)(nil),                           // 31: DeleteProgressLogResponse
	(*GetLastCheckpointRequest)(nil),                            // 32: GetLastCheckpointRequest
	(*GetLastCheckpointResponse)(nil),                           // 33: GetLastCheckpointResponse
	(*Event)(nil),                                               // 34: Event
	(*CreateEventRequest)(nil),                                  // 35: CreateEventRequest
	(*CreateEventResponse)(nil),                                 // 36: CreateEventResponse
	(*ReadEventRequest)(nil),                                    // 37: ReadEventRequest
	(*ReadEventResponse)(nil),                                   // 38: ReadEventResponse
	(*UpdateEventRequest)(nil),                                  // 39: UpdateEventRequest
	(*UpdateEventResponse)(nil),                                 // 40: UpdateEventResponse
	(*ListEventRequest)(nil),                                    // 41: ListEventRequest
	(*ListEventResponse)(nil),                                   // 42: ListEventResponse
	(*RemoveEventRequest)(nil),                                  // 43: RemoveEventRequest
	(*RemoveEventResponse)(nil),                                 // 44: RemoveEventResponse
	(*ListTasksRequest)(nil),                                    // 45: ListTasksRequest
	(*ListTasksResponse)(nil),                                   // 46: ListTasksResponse
	(*ListScheduledTasksResponse_ScheduledTask)(nil),            // 47: ListScheduledTasksResponse.ScheduledTask
	(*ListProgressUpdatesResponse_ProgressLog)(nil),             // 48: ListProgressUpdatesResponse.ProgressLog
	(*ListProgressUpdatesResponse_ProgressLog_UpdatedTask)(nil), // 49: ListProgressUpdatesResponse.ProgressLog.UpdatedTask
	(*ProgressUpdateRequest_UpdatedTask)(nil),                   // 50: ProgressUpdateRequest.UpdatedTask
	(*EditProgressLogRequest_UpdatedTask)(nil),                  // 51: EditProgressLogRequest.UpdatedTask
	(*durationpb.Duration)(nil),                                 // 52: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),                               // 53: google.protobuf.Timestamp
	(*commonpb.Entry)(nil),                                      // 54: Entry
	(*commonpb.Interval)(nil),                                   // 55: Interval
}
var file_apipb_api_proto_depIdxs = []int32{
	52, // 0: PERT.pes:type_name -> google.protobuf.Duration
	52, // 1: PERT.exp:type_name -> google.protobuf.Duration
	52, // 2: PERT.opt:type_name -> google.protobuf.Duration
	1,  // 3: DurState.pert:type_name -> PERT
	53, // 4: DurState.deadline:type_name -> google.protobuf.Timestamp
	53, // 5: ChildrenConfigState.deadline:type_name -> google.protobuf.Timestamp
	54, // 6: ChildrenConfigState.children:type_name -> Entry
	2,  // 7: TaskState.duration_cfg:type_name -> DurState
	3,  // 8: TaskState.children_cfgs:type_name -> ChildrenConfigState
	54, // 9: TaskState.prereqs:type_name -> Entry
	54, // 10: TaskState.postreqs:type_name -> Entry
	54, // 11: TaskState.parent:type_name -> Entry
	53, // 12: TaskState.start:type_name -> google.protobuf.Timestamp
	53, // 13: TaskState.end:type_name -> google.protobuf.Timestamp
	52, // 14: CreateProfileRequest.atomic_timescale:type_name -> google.protobuf.Duration
	53, // 15: CreateProfileRequest.universe_start:type_name -> google.protobuf.Timestamp
	52, // 16: Profile.atomic_timescale:type_name -> google.protobuf.Duration
	53, // 17: Profile.universe_start:type_name -> google.protobuf.Timestamp
	7,  // 18: ListProfilesResponse.entries:type_name -> Profile
	4,  // 19: ReadTaskResponse.state:type_name -> TaskState
	4,  // 20: SaveTaskRequest.state:type_name -> TaskState
	55, // 21: RecomputeScheduleRequest.horizon:type_name -> Interval
	53, // 22: ListScheduledTasksRequest.start:type_name -> google.protobuf.Timestamp
	53, // 23: ListScheduledTasksRequest.end:type_name -> google.protobuf.Timestamp
	47, // 24: ListScheduledTasksResponse.entries:type_name -> ListScheduledTasksResponse.ScheduledTask
	0,  // 25: ListPossibleRelativesRequest.type:type_name -> ListPossibleRelativesRequest.RelativeType
	54, // 26: ListPossibleRelativesResponse.entries:type_name -> Entry
	53, // 27: ListProgressUpdatesRequest.start:type_name -> google.protobuf.Timestamp
	53, // 28: ListProgressUpdatesRequest.end:type_name -> google.protobuf.Timestamp
	48, // 29: ListProgressUpdatesResponse.logs:type_name -> ListProgressUpdatesResponse.ProgressLog
	53, // 30: ProgressUpdateRequest.time:type_name -> google.protobuf.Timestamp
	50, // 31: ProgressUpdateRequest.updates:type_name -> ProgressUpdateRequest.UpdatedTask
	53, // 32: EditProgressLogRequest.time:type_name -> google.protobuf.Timestamp
	51, // 33: EditProgressLogRequest.updates:type_name -> EditProgressLogRequest.UpdatedTask
	53, // 34: GetLastCheckpointResponse.time:type_name -> google.protobuf.Timestamp
	53, // 35: Event.start:type_name -> google.protobuf.Timestamp
	53, // 36: Event.end:type_name -> google.protobuf.Timestamp
	34, // 37: CreateEventRequest.event:type_name -> Event
	34, // 38: ReadEventResponse.event:type_name -> Event
	34, // 39: UpdateEventRequest.event:type_name -> Event
	54, // 40: ListEventResponse.entries:type_name -> Entry
	54, // 41: ListTasksResponse.tasks:type_name -> Entry
	52, // 42: ListScheduledTasksResponse.ScheduledTask.duration:type_name -> google.protobuf.Duration
	53, // 43: ListProgressUpdatesResponse.ProgressLog.time:type_name -> google.protobuf.Timestamp
	49, // 44: ListProgressUpdatesResponse.ProgressLog.updates:type_name -> ListProgressUpdatesResponse.ProgressLog.UpdatedTask
	54, // 45: ListProgressUpdatesResponse.ProgressLog.UpdatedTask.task:type_name -> Entry
	8,  // 46: API.ListProfiles:input_type -> ListProfilesRequest
	5,  // 47: API.CreateProfile:input_type -> CreateProfileRequest
	10, // 48: API.RemoveProfile:input_type -> RemoveProfileRequest
	45, // 49: API.ListTasks:input_type -> ListTasksRequest
	12, // 50: API.ReadTask:input_type -> ReadTaskRequest
	14, // 51: API.SaveTask:input_type -> SaveTaskRequest
	16, // 52: API.DeleteTask:input_type -> DeleteTaskRequest
	22, // 53: API.ListPossibleRelatives:input_type -> ListPossibleRelativesRequest
	18, // 54: API.RecomputeSchedule:input_type -> RecomputeScheduleRequest
	20, // 55: API.ListScheduledTasks:input_type -> ListScheduledTasksRequest
	24, // 56: API.ListProgressUpdates:input_type -> ListProgressUpdatesRequest
	26, // 57: API.ProgressUpdate:input_type -> ProgressUpdateRequest
	28, // 58: API.EditProgressLog:input_type -> EditProgressLogRequest
	30, // 59: API.DeleteProgressLog:input_type -> DeleteProgressLogRequest
	32, // 60: API.GetLastCheckpoint:input_type -> GetLastCheckpointRequest
	35, // 61: API.CreateEvent:input_type -> CreateEventRequest
	37, // 62: API.ReadEvent:input_type -> ReadEventRequest
	39, // 63: API.UpdateEvent:input_type -> UpdateEventRequest
	41, // 64: API.ListEvent:input_type -> ListEventRequest
	43, // 65: API.RemoveEvent:input_type -> RemoveEventRequest
	9,  // 66: API.ListProfiles:output_type -> ListProfilesResponse
	6,  // 67: API.CreateProfile:output_type -> CreateProfileResponse
	11, // 68: API.RemoveProfile:output_type -> RemoveProfileResponse
	46, // 69: API.ListTasks:output_type -> ListTasksResponse
	13, // 70: API.ReadTask:output_type -> ReadTaskResponse
	15, // 71: API.SaveTask:output_type -> SaveTaskResponse
	17, // 72: API.DeleteTask:output_type -> DeleteTaskResponse
	23, // 73: API.ListPossibleRelatives:output_type -> ListPossibleRelativesResponse
	19, // 74: API.RecomputeSchedule:output_type -> RecomputeScheduleResponse
	21, // 75: API.ListScheduledTasks:output_type -> ListScheduledTasksResponse
	25, // 76: API.ListProgressUpdates:output_type -> ListProgressUpdatesResponse
	27, // 77: API.ProgressUpdate:output_type -> ProgressUpdateResponse
	29, // 78: API.EditProgressLog:output_type -> EditProgressLogResponse
	31, // 79: API.DeleteProgressLog:output_type -> DeleteProgressLogResponse
	33, // 80: API.GetLastCheckpoint:output_type -> GetLastCheckpointResponse
	36, // 81: API.CreateEvent:output_type -> CreateEventResponse
	38, // 82: API.ReadEvent:output_type -> ReadEventResponse
	40, // 83: API.UpdateEvent:output_type -> UpdateEventResponse
	42, // 84: API.ListEvent:output_type -> ListEventResponse
	44, // 85: API.RemoveEvent:output_type -> RemoveEventResponse
	66, // [66:86] is the sub-list for method output_type
	46, // [46:66] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_apipb_api_proto_init() }
func file_apipb_api_proto_init() {
	if File_apipb_api_proto != nil {
		return
	}
	file_apipb_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_apipb_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_apipb_api_proto_msgTypes[3].OneofWrappers = []any{}
	file_apipb_api_proto_msgTypes[6].OneofWrappers = []any{}
	file_apipb_api_proto_msgTypes[13].OneofWrappers = []any{}
	file_apipb_api_proto_msgTypes[19].OneofWrappers = []any{}
	file_apipb_api_proto_msgTypes[32].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apipb_api_proto_rawDesc), len(file_apipb_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   51,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apipb_api_proto_goTypes,
		DependencyIndexes: file_apipb_api_proto_depIdxs,
		EnumInfos:         file_apipb_api_proto_enumTypes,
		MessageInfos:      file_apipb_api_proto_msgTypes,
	}.Build()
	File_apipb_api_proto = out.File
	file_apipb_api_proto_goTypes = nil
	file_apipb_api_proto_depIdxs = nil
}
