// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"database/sql"
	"time"
)

type Child struct {
	Parent int64
	Child  int64
}

type ChildrenConfig struct {
	ID        int64
	Task      int64
	Desc      string
	Deadline  sql.NullTime
	ExpCost   sql.NullInt64
	TotalCost sql.NullInt64
}

type ChildrenConfigChild struct {
	Cfg   int64
	Child int64
}

type DurConfig struct {
	ID        int64
	Task      int64
	Pes       int64
	Exp       int64
	Opt       int64
	Deadline  sql.NullTime
	TotalCost sql.NullInt64
}

type Event struct {
	ID      int64
	Profile int64
	Name    string
	Desc    string
	Start   time.Time
	End     time.Time
}

type Prereq struct {
	Prereq  int64
	Postreq int64
}

type Profile struct {
	ID                      int64
	Name                    string
	AtomicTimescaleDuration int64
	UniverseStart           time.Time
	PertGenChoices          sql.NullInt64
}

type ProgressLog struct {
	ID      int64
	Profile int64
	Time    time.Time
	Desc    string
}

type ScheduledTask struct {
	Task    int64
	Profile int64
	Start   time.Time
	End     time.Time
}

type Task struct {
	ID      int64
	Profile int64
	Unit    int64
	Name    string
	Desc    string
	Start   sql.NullTime
	End     sql.NullTime
}

type UpdatedTask struct {
	ProgressLog int64
	Task        int64
	Desc        string
}
