// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addChildToConfig = `-- name: AddChildToConfig :exec
insert into children_config_child (cfg, child)
values (?, ?) on conflict do nothing
`

type AddChildToConfigParams struct {
	Cfg   int64
	Child int64
}

func (q *Queries) AddChildToConfig(ctx context.Context, arg AddChildToConfigParams) error {
	_, err := q.db.ExecContext(ctx, addChildToConfig, arg.Cfg, arg.Child)
	return err
}

const createAlloc = `-- name: CreateAlloc :exec
insert into allocation (task, desc, start, end)
values (?, ?, ?, ?) on conflict do nothing
`

type CreateAllocParams struct {
	Task  int64
	Desc  string
	Start time.Time
	End   time.Time
}

func (q *Queries) CreateAlloc(ctx context.Context, arg CreateAllocParams) error {
	_, err := q.db.ExecContext(ctx, createAlloc,
		arg.Task,
		arg.Desc,
		arg.Start,
		arg.End,
	)
	return err
}

const createChildrenConfig = `-- name: CreateChildrenConfig :exec
insert into children_config (task, desc, deadline, exp_cost)
values (?, ?, ?, ?)
`

type CreateChildrenConfigParams struct {
	Task     int64
	Desc     string
	Deadline sql.NullInt64
	ExpCost  sql.NullInt64
}

func (q *Queries) CreateChildrenConfig(ctx context.Context, arg CreateChildrenConfigParams) error {
	_, err := q.db.ExecContext(ctx, createChildrenConfig,
		arg.Task,
		arg.Desc,
		arg.Deadline,
		arg.ExpCost,
	)
	return err
}

const createDurConfig = `-- name: CreateDurConfig :exec
insert into dur_config (task, pes, exp, opt, deadline, total_cost)
values (?, ?, ?, ?, ?, ?)
`

type CreateDurConfigParams struct {
	Task      int64
	Pes       int64
	Exp       int64
	Opt       int64
	Deadline  sql.NullInt64
	TotalCost sql.NullInt64
}

func (q *Queries) CreateDurConfig(ctx context.Context, arg CreateDurConfigParams) error {
	_, err := q.db.ExecContext(ctx, createDurConfig,
		arg.Task,
		arg.Pes,
		arg.Exp,
		arg.Opt,
		arg.Deadline,
		arg.TotalCost,
	)
	return err
}

const createTask = `-- name: CreateTask :exec
insert into task (profile, unit, name, desc) values (?, ?, ?, ?)
`

type CreateTaskParams struct {
	Profile int64
	Unit    int64
	Name    string
	Desc    string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.Profile,
		arg.Unit,
		arg.Name,
		arg.Desc,
	)
	return err
}

const listProfiles = `-- name: ListProfiles :many
select id, name, universe_start from profile
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(&i.ID, &i.Name, &i.UniverseStart); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimescales = `-- name: ListTimescales :many
select name, size from timescale_unit where profile = ?
order by size asc
`

type ListTimescalesRow struct {
	Name string
	Size int64
}

func (q *Queries) ListTimescales(ctx context.Context, profile int64) ([]ListTimescalesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTimescales, profile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimescalesRow
	for rows.Next() {
		var i ListTimescalesRow
		if err := rows.Scan(&i.Name, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChild = `-- name: SetChild :exec
insert into child (parent, child)
values (?, ?) on conflict do nothing
`

type SetChildParams struct {
	Parent int64
	Child  int64
}

func (q *Queries) SetChild(ctx context.Context, arg SetChildParams) error {
	_, err := q.db.ExecContext(ctx, setChild, arg.Parent, arg.Child)
	return err
}

const setPrereq = `-- name: SetPrereq :exec
insert into prereq (prereq, postreq)
values (?, ?) on conflict do nothing
`

type SetPrereqParams struct {
	Prereq  int64
	Postreq int64
}

func (q *Queries) SetPrereq(ctx context.Context, arg SetPrereqParams) error {
	_, err := q.db.ExecContext(ctx, setPrereq, arg.Prereq, arg.Postreq)
	return err
}
