// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: query.sql

package db

import (
	"context"
)

const listProfiles = `-- name: ListProfiles :many
select id, name, universe_start from profile
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(&i.ID, &i.Name, &i.UniverseStart); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimescales = `-- name: ListTimescales :many
select name, size from timescale_unit where profile = ?
order by size asc
`

type ListTimescalesRow struct {
	Name string
	Size int64
}

func (q *Queries) ListTimescales(ctx context.Context, profile int64) ([]ListTimescalesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTimescales, profile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimescalesRow
	for rows.Next() {
		var i ListTimescalesRow
		if err := rows.Scan(&i.Name, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
