// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addChildToConfig = `-- name: AddChildToConfig :exec
insert into children_config_child (cfg, child)
values (?, ?) on conflict do nothing
`

type AddChildToConfigParams struct {
	Cfg   int64
	Child int64
}

func (q *Queries) AddChildToConfig(ctx context.Context, arg AddChildToConfigParams) error {
	_, err := q.db.ExecContext(ctx, addChildToConfig, arg.Cfg, arg.Child)
	return err
}

const createAlloc = `-- name: CreateAlloc :exec
insert into allocation (task, desc, start, end)
values (?, ?, ?, ?) on conflict do nothing
`

type CreateAllocParams struct {
	Task  int64
	Desc  string
	Start time.Time
	End   time.Time
}

func (q *Queries) CreateAlloc(ctx context.Context, arg CreateAllocParams) error {
	_, err := q.db.ExecContext(ctx, createAlloc,
		arg.Task,
		arg.Desc,
		arg.Start,
		arg.End,
	)
	return err
}

const createChildrenConfig = `-- name: CreateChildrenConfig :exec
insert into children_config (task, desc, deadline, exp_cost)
values (?, ?, ?, ?)
`

type CreateChildrenConfigParams struct {
	Task     int64
	Desc     string
	Deadline sql.NullTime
	ExpCost  sql.NullInt64
}

func (q *Queries) CreateChildrenConfig(ctx context.Context, arg CreateChildrenConfigParams) error {
	_, err := q.db.ExecContext(ctx, createChildrenConfig,
		arg.Task,
		arg.Desc,
		arg.Deadline,
		arg.ExpCost,
	)
	return err
}

const createDurConfig = `-- name: CreateDurConfig :exec
insert into dur_config (task, pes, exp, opt, deadline, total_cost)
values (?, ?, ?, ?, ?, ?)
`

type CreateDurConfigParams struct {
	Task      int64
	Pes       int64
	Exp       int64
	Opt       int64
	Deadline  sql.NullTime
	TotalCost sql.NullInt64
}

func (q *Queries) CreateDurConfig(ctx context.Context, arg CreateDurConfigParams) error {
	_, err := q.db.ExecContext(ctx, createDurConfig,
		arg.Task,
		arg.Pes,
		arg.Exp,
		arg.Opt,
		arg.Deadline,
		arg.TotalCost,
	)
	return err
}

const createTask = `-- name: CreateTask :exec
insert into task (profile, unit, name, desc) values (?, ?, ?, ?)
`

type CreateTaskParams struct {
	Profile int64
	Unit    int64
	Name    string
	Desc    string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.Profile,
		arg.Unit,
		arg.Name,
		arg.Desc,
	)
	return err
}

const getDurConfig = `-- name: GetDurConfig :one
select id, task, pes, pes_unit, exp, exp_unit, opt, opt_unit, deadline, total_cost from dur_config where task = ?
`

func (q *Queries) GetDurConfig(ctx context.Context, task int64) (DurConfig, error) {
	row := q.db.QueryRowContext(ctx, getDurConfig, task)
	var i DurConfig
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.Pes,
		&i.PesUnit,
		&i.Exp,
		&i.ExpUnit,
		&i.Opt,
		&i.OptUnit,
		&i.Deadline,
		&i.TotalCost,
	)
	return i, err
}

const getParent = `-- name: GetParent :one
select t.id, t.profile, t.unit, t.name, t.desc from task as t
inner join children_config as c on
	t.id = c.task
inner join children_config_child cc on
	c.id = cc.cfg
where cc.child = ?
group by t.id
`

func (q *Queries) GetParent(ctx context.Context, child int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getParent, child)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.Unit,
		&i.Name,
		&i.Desc,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
select id, profile, unit, name, "desc" from task where id = ?
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Profile,
		&i.Unit,
		&i.Name,
		&i.Desc,
	)
	return i, err
}

const listChildrenConfigChildren = `-- name: ListChildrenConfigChildren :many
select child from children_config_child where cfg = ?
`

func (q *Queries) ListChildrenConfigChildren(ctx context.Context, cfg int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listChildrenConfigChildren, cfg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var child int64
		if err := rows.Scan(&child); err != nil {
			return nil, err
		}
		items = append(items, child)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildrenConfigs = `-- name: ListChildrenConfigs :many
select id, task, "desc", deadline, exp_cost from children_config where task = ?
`

func (q *Queries) ListChildrenConfigs(ctx context.Context, task int64) ([]ChildrenConfig, error) {
	rows, err := q.db.QueryContext(ctx, listChildrenConfigs, task)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChildrenConfig
	for rows.Next() {
		var i ChildrenConfig
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.Desc,
			&i.Deadline,
			&i.ExpCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostreq = `-- name: ListPostreq :many
select postreq from prereq where prereq = ?
`

func (q *Queries) ListPostreq(ctx context.Context, prereq int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPostreq, prereq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var postreq int64
		if err := rows.Scan(&postreq); err != nil {
			return nil, err
		}
		items = append(items, postreq)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrereq = `-- name: ListPrereq :many
select prereq from prereq where postreq = ?
`

func (q *Queries) ListPrereq(ctx context.Context, postreq int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPrereq, postreq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var prereq int64
		if err := rows.Scan(&prereq); err != nil {
			return nil, err
		}
		items = append(items, prereq)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfiles = `-- name: ListProfiles :many
select id, name, universe_start from profile
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(&i.ID, &i.Name, &i.UniverseStart); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimescales = `-- name: ListTimescales :many
select name, size from timescale_unit where profile = ?
order by size asc
`

type ListTimescalesRow struct {
	Name string
	Size int64
}

func (q *Queries) ListTimescales(ctx context.Context, profile int64) ([]ListTimescalesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTimescales, profile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimescalesRow
	for rows.Next() {
		var i ListTimescalesRow
		if err := rows.Scan(&i.Name, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChild = `-- name: SetChild :exec
insert into child (parent, child)
values (?, ?) on conflict do nothing
`

type SetChildParams struct {
	Parent int64
	Child  int64
}

func (q *Queries) SetChild(ctx context.Context, arg SetChildParams) error {
	_, err := q.db.ExecContext(ctx, setChild, arg.Parent, arg.Child)
	return err
}

const setPrereq = `-- name: SetPrereq :exec
insert into prereq (prereq, postreq)
values (?, ?) on conflict do nothing
`

type SetPrereqParams struct {
	Prereq  int64
	Postreq int64
}

func (q *Queries) SetPrereq(ctx context.Context, arg SetPrereqParams) error {
	_, err := q.db.ExecContext(ctx, setPrereq, arg.Prereq, arg.Postreq)
	return err
}
